### ISSUE TITLE
Too many vertices in submesh BUT THERE AREN'T

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1014]
**Describe the bug**
When trying to import a glb file, I get the following error message: 

```
[20/11/2022 20:43:36] Message: Too many vertices (72547) in submesh - max is 65535
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.RawMeshToRE4Mesh(RawMeshContainer mesh, Vector4 qScale, Vector4 qTrans) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 751
   at WolvenKit.Modkit.RED4.ModTools.<>c__DisplayClass63_0.<ImportMesh>b__3(RawMeshContainer _) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 431
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inmeshStream, GltfImportArgs args, Stream outStream) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 431
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 440
```
However:
![image](https://user-images.githubusercontent.com/965785/202922668-d8e66a38-7d42-4496-94b5-76672163c3b4.png)

I'm not entirely sure what's wrong with the glb and why it's so big (all troubleshooting tools tell me it's fine, yet it has almost 5MB compared to the un-warped original with ~1.5), but the number of vertices certainly ain't it.

**To Reproduce**
1. Put octopus.mesh somewhere under "archive" and octopus.glb under "raw"
2. use WKit importer to import glb over mesh 

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version WolvenKit-8.8.1-nightly.2022-11-19

[mesh.zip](https://github.com/WolvenKit/WolvenKit/files/10055499/mesh.zip)

**Comment by dragonzkiller** [comment]
Your GLB in Blender:
![Screenshot 2022-11-24 115931](https://user-images.githubusercontent.com/931177/203857096-b624c094-ebd5-48e7-8bb9-094cb3315be6.png)

**Comment by manavortex** [comment]
... interesting. Something must be really broken on my end, then - I even tried reimporting it into a clean file.

I guess this is an ID-10t, then. Thank you for pointing me towards that :)
