### ISSUE TITLE
Presence of .Material.json in folder causes exception upon bulk import

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1026]
**Describe the bug**
When trying to mass import files from json, the process fails as soon as there are Material.json files in the folder.
I generated those the day before while trying to test Silmarilius's export script, so it was probably via "export all (experimental)" from my custom ent.

**To Reproduce**
1. In the attached archive, right-click on the folder "raw/…/biker_pants" and select "Convert from JSON".

**Expected behavior**
I have several ideas, but the behaviour I'm currently observing is not it :D As far as I know, json import still overwrites original files. Maybe it could check if a file to import over is present, and at the end of the process, show the user a message which files have been skipped?

**Stacktrace**
```
[04/12/2022 09:31:10] Finished loading Archive Manager.
[04/12/2022 09:31:15] Unhandled exception in WolvenKit v8.8.1.0
[04/12/2022 09:31:15] Message: The JSON value could not be converted to WolvenKit.Common.Conversion.RedFileDto. Path: $ | LineNumber: 1 | BytePositionInLine: 17.
Source: WolvenKit.Common
StackTrace:    at WolvenKit.RED4.CR2W.JSON.RedFileDtoConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\CR2W\JSON\RedFileDtoConverter.cs:line 46
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at WolvenKit.RED4.CR2W.JSON.RedJsonSerializer.Deserialize[T](String json) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\CR2W\JSON\RedJsonSerializer.cs:line 149
   at WolvenKit.Modkit.RED4.ModTools.ConvertFromJson(String json) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\RedConverter.cs:line 93
   at WolvenKit.Modkit.RED4.ModTools.ConvertFromAndWrite(FileInfo fileInfo, DirectoryInfo outputDirInfo) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\RedConverter.cs:line 119
   at WolvenKit.ViewModels.Tools.ProjectExplorerViewModel.<>c__DisplayClass142_0.<ConvertFromTask>b__0() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ProjectExplorerViewModel.cs:line 565
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WolvenKit.ViewModels.Tools.ProjectExplorerViewModel.ExecuteConvertFromAsync() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ProjectExplorerViewModel.cs:line 530
   at WolvenKit.ViewModels.Tools.ProjectExplorerViewModel.<.ctor>b__11_24() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ProjectExplorerViewModel.cs:line 103
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
**Note**: The stacktrace doesn't contain the name or path of the conflicting file, which is not optimal.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version WolvenKit-8.8.1-nightly.2022-11-29

[source.zip](https://github.com/WolvenKit/WolvenKit/files/10148113/source.zip)

**Comment by Simarilius-uk** [comment]
Probably my fault, the change I made to the material json to include the appearance info, I didnt do anything to the input side of things.
