### ISSUE TITLE
Rebuild: Adding/Removing buffers is not supported

### ISSUE THREAD

**Issue by gewfsmc** [WolvenKit/WolvenKit#1097]
Getting this error when trying to import:
`PS E:\wolvenkitconsole2> .\WolvenKit.CLI.exe import -k -p "E:\archives\Judy"
[ 0: Information ] - Found 1 raw file(s) to rebuild
[ 0: Warning     ] - Unused buffer found!
Unhandled exception: System.NotSupportedException: Rebuild: Adding/Removing buffers is not supported
   at WolvenKit.Modkit.RED4.ModTools.<Rebuild>g__AppendBuffersToFile|28_0(Stream fileStream, <>c__DisplayClass28_0&) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Rebuild.cs:line 110
   at WolvenKit.Modkit.RED4.ModTools.Rebuild(Stream redfileStream, IEnumerable`1 buffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Rebuild.cs:line 71
   at WolvenKit.Modkit.RED4.ModTools.RebuildFolder(DirectoryInfo inDir, DirectoryInfo outDir) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Rebuild.cs:line 283
   at WolvenKit.Modkit.RED4.ModTools.ImportFolder(DirectoryInfo inDir, GlobalImportArgs args, DirectoryInfo outDir) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 254
   at CP77Tools.Tasks.ConsoleFunctions.ImportTaskInner(FileSystemInfo path, DirectoryInfo outDirectory, Boolean keep) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tasks\ImportTask.cs:line 110
   at CP77Tools.Tasks.ConsoleFunctions.ImportTask(FileSystemInfo[] path, DirectoryInfo outDir, Boolean keep) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tasks\ImportTask.cs:line 32
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
   at CP77Tools.Commands.CommandBase.ActionBase(InvocationContext context) in D:\a\WolvenKit\WolvenKit\WolvenKit.CLI\Commands\CommandBase.cs:line 26
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.SyncUsingAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
PS E:\wolvenkitconsole2>`

Any ideas how to work around it? wolvenkit console

**Comment by rfuzzo** [comment]
Hmm, what file are you trying to import here?

**Comment by gewfsmc** [comment]
judy.app Following a guide written by one of AMM's devs to add custom AMM appearances to NPCs

**Comment by rfuzzo** [comment]
thanks, can you link the guide please?

**Comment by gewfsmc** [comment]
Sure, so I'm following two things:
https://www.youtube.com/watch?v=BroxxDenpi4&t=443s
and written guide:
https://drive.google.com/file/d/1VZFhnFg-eHMaWGNIWY0EpAEpoLsRD8aH/view?usp=share_link

**Comment by rfuzzo** [comment]
Hmm, thanks. This guide is quite old, and uses 010 editor and the (outdated) save editor... 

WolvenKit app supports editing buffers and app files now, so I'm not sure if we will add support for this kind of outdated buffer editing. 

I also don't even have 010 editor installed, and the save editor is not updated for patch 1.6. So, all in all, I see very little chance this is supported. But I'll keep the issue open in case someone wants to look into it.

**Comment by gewfsmc** [comment]
I see. Thanks for that. Since AFAIK, that's the only guide available to do what I'm trying to, could you tell me which version was the last to support this kind of buffer editing? Plus, if there is a repo of archived wolvenkit versions?

**Comment by rfuzzo** [comment]
The ways to install Wolvenkit are described in the readme

There are multiple ways to install Wolvenkit:

### The WolvenKit.Installer app

The WolvenKit.Installer app is a simple program for managing (installing, updating, removing) different WolvenKit versions similar to the Visual Studio Installer app. 

It is [hosted on github](https://github.com/WolvenKit/WolvenKit.Installer) and you can install it from there. Click here: [![GitHub release (latest by date)](https://img.shields.io/github/v/release/WolvenKit/WolvenKit.Installer)](https://github.com/WolvenKit/WolvenKit.Installer/releases/latest)

### Portable or Installer

Download either the latest stable version or the current nightly (beta) version from here:

| Package | Latest Release | Checks  |
| ------- | ------------ | ----------------- |
| [WolvenKit Nightly](https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/latest) | [![GitHub release (latest by date)](https://img.shields.io/github/v/release/WolvenKit/WolvenKit-nightly-releases)](https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/latest) | ![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/WolvenKit/WolvenKit/nightly.yml) |
| [WolvenKit](https://github.com/WolvenKit/WolvenKit/releases/latest) | [![GitHub release (latest by date)](https://img.shields.io/github/v/release/WolvenKit/WolvenKit)](https://github.com/WolvenKit/WolvenKit/releases/latest) | ![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/WolvenKit/WolvenKit/check-only.yml) | 

To install the app quickly download `WolvenKitSetup-x.x.x.exe` and double click to run the installer.

You can also simply download `WolvenKit-x.x.x.x.zip` and extract it to a location of your choice

**Comment by rfuzzo** [comment]
old versions are also under these links, with the Releases

**Comment by Simarilius-uk** [comment]
You could just do it all in wkit. 
https://wiki.redmodding.org/cyberpunk-2077-modding/modding-guides/npcs/appearances-change-the-looks

**Comment by gewfsmc** [comment]
Oh, thanks! Really appreciate it guys.

**Comment by Simarilius-uk** [comment]
come ask in the Discord in texture-and-models if you have any issues :)
