### ISSUE TITLE
Import Tool not opening (Exception)

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1106]
**Describe the bug**

1. Import the attached project: [NPVee.zip](https://github.com/WolvenKit/WolvenKit/files/10474042/NPVee.zip)
2. Try to open the Import Manager via Tools 
3. Behold the exception: 
```
[22/01/2023 09:55:25] Archive Manager loaded in 1465ms
[22/01/2023 09:55:29] Finished loading Archive Manager.
[22/01/2023 09:55:55] Unhandled exception in WolvenKit v8.8.1.0
[22/01/2023 09:55:55] Message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Source: System.Private.CoreLib
StackTrace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.TexHelperImpl.LoadFromDDSFile(String szFile, DDS_FLAGS flags, TexMetadata& metadata)
   at WolvenKit.RED4.CR2W.RedImage.LoadFromDDSFile(String szFile, DXGI_FORMAT format) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\RedImage.cs:line 144
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel.LoadXbmDefaultSettings() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 101
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel.DecideImportOptions() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 57
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel..ctor(String fileName) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 26
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel.<>c.<LoadFiles>b__8_0(String x) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 254
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel.LoadFiles() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 257
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel..ctor(IGameControllerFactory gameController, ISettingsManager settingsManager, IWatcherService watcherService, ILoggerService loggerService, IProjectManager projectManager, INotificationService notificationService, IArchiveManager archiveManager, IPluginService pluginService, IModTools modTools, IProgressService`1 progressService) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 67
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetServices(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 113
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 86
   at Splat.DependencyResolverMixins.GetService[T](IReadonlyDependencyResolver resolver, String contract) in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 31
   at WolvenKit.ViewModels.Shell.AppViewModel.ShowTextureImporter() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\AppViewModel.cs:line 1086
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in /_/src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs:line 105
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:line 58
[22/01/2023 09:56:07] Unhandled exception in WolvenKit v8.8.1.0
[22/01/2023 09:56:07] Message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Source: System.Private.CoreLib
StackTrace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.TexHelperImpl.LoadFromDDSFile(String szFile, DDS_FLAGS flags, TexMetadata& metadata)
   at WolvenKit.RED4.CR2W.RedImage.LoadFromDDSFile(String szFile, DXGI_FORMAT format) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\RedImage.cs:line 144
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel.LoadXbmDefaultSettings() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 101
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel.DecideImportOptions() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 57
   at WolvenKit.ViewModels.Tools.ImportableItemViewModel..ctor(String fileName) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportableItemViewModel.cs:line 26
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel.<>c.<LoadFiles>b__8_0(String x) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 254
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel.LoadFiles() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 257
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel..ctor(IGameControllerFactory gameController, ISettingsManager settingsManager, IWatcherService watcherService, ILoggerService loggerService, IProjectManager projectManager, INotificationService notificationService, IArchiveManager archiveManager, IPluginService pluginService, IModTools modTools, IProgressService`1 progressService) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 67
   at InvokeStub_TextureImportViewModel..ctor(Object, Object, IntPtr*)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetServices(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 113
   at Splat.Microsoft.Extensions.DependencyInjection.MicrosoftDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs:line 86
   at Splat.DependencyResolverMixins.GetService[T](IReadonlyDependencyResolver resolver, String contract) in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 31
   at WolvenKit.ViewModels.Shell.AppViewModel.ShowTextureImporter() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\AppViewModel.cs:line 1086
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in /_/src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs:line 105
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:line 58
```

Win10 x64, WolvenKit-8.8.2-nightly.2023-01-19

**Comment by rfuzzo** [comment]
That's actually a problem with a texture, can you either narrow it down to one texture and send me that one, or send me your  /raw folder?

**Comment by manavortex** [comment]
I attached the entire project, it has most of the raw folder

**Comment by rfuzzo** [comment]
thanks 👍 (I should maybe start reading)

**Comment by seberoth** [comment]
We should catch these errors, but it happens because all these dds files only contain the dds header without actual image data.

**Comment by rfuzzo** [comment]
this is already fixed on main, the PR is to make loading non-blocking
