### ISSUE TITLE
Mesh won't export (Exception)

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1112]
Upon trying to export the attached mesh, I get an exception:

[wont_export.zip](https://github.com/WolvenKit/WolvenKit/files/10502133/wont_export.zip)

```
[25/01/2023 18:47:02] manavortex\subfolder\meshes\wont_export.mesh - Value cannot be null. (Parameter 'srcBones.AposeLSScale')
[25/01/2023 18:47:02] Message: Value cannot be null. (Parameter 'srcBones.AposeLSScale')
Source: System.Private.CoreLib
StackTrace:    at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at WolvenKit.Modkit.RED4.RigFile.RIG.ExportNodes(ModelRoot& model, RawArmature srcBones) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\RigTools.cs:line 178
   at WolvenKit.Modkit.RED4.Tools.MeshTools.RawMeshesToGLTF(List`1 meshes, RawArmature rig, Boolean mergeMeshes, Boolean withMaterials) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 1008
   at WolvenKit.Modkit.RED4.Tools.MeshTools.GetModel(CR2WFile cr2w, Boolean lodFilter, Boolean includeRig, UInt64 chunkMask, Boolean mergeMeshes, Boolean exportGarmentSupport) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 86
   at WolvenKit.Modkit.RED4.Tools.MeshTools.ExportMesh(CR2WFile cr2w, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 34
   at WolvenKit.Modkit.RED4.ModTools.ExportMesh(Stream meshStream, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 857
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(Stream cr2wStream, FileInfo cr2wFileName, MeshExportArgs meshargs) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 865
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 432
[25/01/2023 18:47:03] 0/1 files have been processed and are available in the Project Explorer
[25/01/2023 18:47:03] The following items failed:
E:\CyberpunkFiles\other\project\source\archive\manavortex\subfolder\meshes\wont_export.mesh
```
Export settings: 
![image](https://user-images.githubusercontent.com/965785/214642427-988953a9-7fb8-4da2-8a47-31e69a852447.png)

The same happens with any states of Export Materials and Export Garment Support.

Changing the export type to WithRig will lead to export failure without exception.

**Comment by dragonzkiller** [comment]
Potentially fixed this on my fork. Will submit a PR for it later
