### ISSUE TITLE
Exception when trying to import (flat) mesh

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1119]
When trying to re-import a completely flat (2dimensional) mesh, there's an exception:

```
[27/01/2023 22:48:04] Message: Value was either too large or too small for an Int32.
Source: System.Private.CoreLib
StackTrace:    at System.Convert.ToInt32(Double value)
   at System.Convert.ToInt16(Single value)
   at WolvenKit.Modkit.RED4.ModTools.RawMeshToRE4Mesh(RawMeshContainer mesh, Vector4 qScale, Vector4 qTrans) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 665
   at WolvenKit.Modkit.RED4.ModTools.<>c__DisplayClass63_0.<ImportMesh>b__3(RawMeshContainer _) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 431
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inmeshStream, GltfImportArgs args, Stream outStream) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 431
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 447
[27/01/2023 22:48:04] 0/1 files have been processed and are available in the Project Explorer
[27/01/2023 22:48:04] The following items failed:
E:\CyberpunkFiles\AMM_stuff\AMM_pink_props\source\raw\manavortex\amm_props\pink_stuff\posters\poster.glb
```

**To Reproduce**
1. Add a poster to your project (e.g. `base\environment\decoration\advertising\posters\poster\poster_f.mesh`)
2. Export it to glb
3. Import it to Blender, then export it to glb again (might not be necessary)
4. Import it to WolvenKit

**Comment by dragonzkiller** [comment]
Potentially fixed this on my fork. Will submit a PR for it later
