### ISSUE TITLE
Mesh export fail

### ISSUE THREAD

**Issue by yraven1** [WolvenKit/WolvenKit#1131]
Only happens to a certain custom mesh, works normally in game but when exporting it throw this error log:

[01/02/2023 00:49:44] Message: Index was outside the bounds of the array.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.RigFile.RIG.ExportNodes(ModelRoot& model, RawArmature srcBones) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\RigTools.cs:line 162
   at WolvenKit.Modkit.RED4.Tools.MeshTools.RawMeshesToGLTF(List`1 meshes, RawArmature rig, Boolean mergeMeshes) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 1025
   at WolvenKit.Modkit.RED4.ModTools.ExportMeshWithMaterials(Stream meshStream, FileInfo outfile, MeshExportArgs meshArgs, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 59
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(Stream cr2wStream, FileInfo cr2wFileName, MeshExportArgs meshargs) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 693
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 426

**Comment by yraven1** [comment]
Best part is, on File Information i can have a preview of the mesh, but when i try Mesh Preview...:
[01/02/2023 02:49:00] Unhandled exception in WolvenKit v8.8.1.0
[01/02/2023 02:49:00] Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source: System.Private.CoreLib
StackTrace:    at WolvenKit.RED4.Types.CArrayBase`1.get_Item(Int32 index) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Types\Primitives\CArrayBase.cs:line 189
   at WolvenKit.ViewModels.Documents.RDTMeshViewModel.RenderMesh() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Documents\RDTMeshViewModel.cs:line 302
   at WolvenKit.ViewModels.Documents.RDTMeshViewModel.<.ctor>b__103_0(CompositeDisposable disposables) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Documents\RDTMeshViewModel.cs:line 264
   at ReactiveUI.ViewForMixins.<>c__DisplayClass4_0.<WhenActivated>b__0() in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 101
   at ReactiveUI.ViewModelActivator.<>c.<Activate>b__10_1(Func`1 x) in /_/src/ReactiveUI/Activation/ViewModelActivator.cs:line 83
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Reactive.Disposables.CompositeDisposable.ToList(IEnumerable`1 disposables) in /_/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs:line 113
   at System.Reactive.Disposables.CompositeDisposable..ctor(IEnumerable`1 disposables) in /_/Rx.NET/Source/src/System.Reactive/Disposables/CompositeDisposable.cs:line 80
   at ReactiveUI.ViewModelActivator.Activate() in /_/src/ReactiveUI/Activation/ViewModelActivator.cs:line 83
   at ReactiveUI.ViewForMixins.<>c__DisplayClass11_0.<HandleViewModelActivation>b__3(IActivatableViewModel x) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 275
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 104
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 124
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.Run(IEnumerable`1 source, IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 56
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.TailRecursiveSink`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 187
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 35
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 60
   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1.Run(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs:line 64
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 43
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 66
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 148
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 51
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at ReactiveUI.ViewForMixins.<>c__DisplayClass11_0.<HandleViewModelActivation>b__0(Boolean activated) in /_/src/ReactiveUI/Activation/ViewForMixins.cs:line 262
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by seberoth** [comment]
> Only happens to a certain custom mesh
Would be nice if you could attach the mesh then.

**Comment by thedragonboose** [comment]
Also if you want to see the mesh it's not mine, i was making a personal edit to it, it's Anrui's Kerry Neck Cyberware - Male V.

The base mesh is the one i can't extract, seems to happen with all base mesh no matter what, be it full mesh or specific part mesh.

**Comment by thedragonboose** [comment]
And the conclusion is, if there's more bonePositions than boneNames, boneRigMatrices or boneVertexEpsilons. WolvenKit just don't export it and throw this error, deleting the extra bonePositions seems to allow export for some reason.
