### ISSUE TITLE
Can not export w_handgun__tsunami_nue__base1.anims

### ISSUE THREAD

**Issue by DeltaDesigns** [WolvenKit/WolvenKit#1137]
Trying to export "w_handgun__tsunami_nue__base1.anims" results in an error, other anim for the mag of the weapon exports fine

```
[2/2/2023 8:39:22 PM] base\animations\weapon\firearms\handgun\tsunami_nue\w_handgun__tsunami_nue__base1.anims - Index was outside the bounds of the array.
[2/2/2023 8:39:22 PM] Message: Index was outside the bounds of the array.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.Animation.SIMD.AddAnimationSIMD(ModelRoot& model, animAnimationBufferSimd blob, String animName, Stream defferedBuffer, animAnimation animAnimDes, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\Animation\AnimSIMD.cs:line 210
   at WolvenKit.Modkit.RED4.ModTools.GetAnimation(CR2WFile animsFile, CR2WFile rigFile, ModelRoot& model, Boolean includeRig, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 333
   at WolvenKit.Modkit.RED4.ModTools.ExportAnim(CR2WFile animsFile, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 61
   at WolvenKit.Modkit.RED4.ModTools.ExportAnim(Stream animStream, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 28
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 559
```

Using WolvenKit-8.8.1

**Comment by eerielocus** [comment]
Running into similar error when trying to export 'pwa_w_revolver__malorian_overture.anims':

> [10/18/2023 3:28:01 PM] [Error    ] base\animations\weapon\firearms\revolver\malorian_overture\pwa_w_revolver__malorian_overture.anims - Index was outside the bounds of the array.
> [10/18/2023 3:28:01 PM] [Error    ] Message: Index was outside the bounds of the array.
> Source: WolvenKit.Modkit
> StackTrace:    at WolvenKit.Modkit.RED4.Animation.SIMD.AddAnimationSIMD(ModelRoot& model, animAnimationBufferSimd blob, String animName, Stream defferedBuffer, animAnimation animAnimDes, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\Animation\AnimSIMD.cs:line 16
>    at WolvenKit.Modkit.RED4.ModTools.GetAnimation(CR2WFile animsFile, CR2WFile rigFile, ModelRoot& model, Boolean includeRig, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 356
>    at WolvenKit.Modkit.RED4.ModTools.ExportAnim(CR2WFile animsFile, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 66
>    at WolvenKit.Modkit.RED4.ModTools.ExportAnim(Stream animStream, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 25
>    at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 469
