### ISSUE TITLE
Unhandled exception when following "Creating a Mod"

### ISSUE THREAD

**Issue by hotxot** [WolvenKit/WolvenKit#1158]
**Describe the bug**
* On step 5 under "Asset Browser" on https://wiki.redmodding.org/wolvenkit/getting-started/creating-a-mod
* When "double-clicking directly on the file" an Unhandled Exception is shown in the log

**Expected behavior**
Expect the texture to be added to the project 

**Version:**
WolvenKit v8.8.1.0
Totally new install

**Log**
[2023-02-14 11:22:04] Unhandled exception in WolvenKit v8.8.1.0
[2023-02-14 11:22:04] Message: The method or operation is not implemented.
Source: WolvenKit.App
StackTrace:    at WolvenKit.Functionality.Controllers.MockGameController.AddFileToModModal(IGameFile file) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Controllers\MockGameController.cs:line 14
   at WolvenKit.ViewModels.Tools.AssetBrowserViewModel.ExecuteOpenFileAsync() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\AssetBrowserViewModel.cs:line 539

**Comment by rfuzzo** [comment]
can't repro
