### ISSUE TITLE
Can't import greyscale pngs

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1164]
Trying to export a png with reduced channels will cause exceptions (occasionally happens with roughness maps for sketchfab). Here's one from a greyscale texture: 

```
[17/02/2023 22:46:46] Could not import feather_01_r.png
[17/02/2023 22:46:46] Message: The request is not supported. (0x80070032)
Source: System.Private.CoreLib
StackTrace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at DirectXTexNet.ScratchImageImpl.PremultiplyAlpha(TEX_PMALPHA_FLAGS flags)
   at WolvenKit.RED4.CR2W.RedImage.GetSetupAndBlob(RedImageTransformSettings settings) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\RedImage.cs:line 515
   at WolvenKit.RED4.CR2W.RedImage.SaveToXBM(XbmImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\RedImage.cs:line 425
   at WolvenKit.Modkit.RED4.ModTools.ImportXbm(RedRelativePath rawRelative, DirectoryInfo outDir, XbmImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 370
   at WolvenKit.Modkit.RED4.ModTools.HandleTextures(RedRelativePath rawRelative, DirectoryInfo outDir, GlobalImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 195
   at WolvenKit.Modkit.RED4.ModTools.Import(RedRelativePath rawRelative, GlobalImportArgs args, DirectoryInfo outDir) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 63
   at WolvenKit.App.ViewModels.Importers.TextureImportViewModel.ImportSingleTask(ImportableItemViewModel item) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\TextureImportViewModel.cs:line 271
[17/02/2023 22:46:47] The following items failed:
E:\CyberpunkFiles\AMM_stuff\AMM_props_office\source\raw\manavortex\amm_props\office\feather\feather_01_r.png
   ```

![basic_metallicRoughness](https://user-images.githubusercontent.com/965785/219799833-6c5a3226-dff4-41b4-9273-7e656bf9f167.png)

8.8.2-nightly.2023-02-16

**Comment by seberoth** [comment]
@rfuzzo PremultiplyAlpha is on by default. Is that intended? (for every filename)
Thought it was only use with `TCM_DXTAlpha`
