### ISSUE TITLE
unable to open (working) ent file

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1175]
[shard_a.zip](https://github.com/WolvenKit/WolvenKit/files/10833729/shard_a.zip)

I can't open the attached entity file.

Nightly 2023-02-25: 
[26/02/2023 14:01:31] Unable to open file: E:\CyberpunkFiles\AMM_stuff\AMM_props_art_and_office\source\archive\base\amm_props\collab\entity\shard_a.ent

Nightly 2023-01-17: 
displays a blank panel

8.7 Stable: 
```
[26/02/2023 13:58:58] Message: Exception has been thrown by the target of an invocation.
Source: System.Private.CoreLib
StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WolvenKit.RED4.IO.Red4Reader.ReadCArray(Type type, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Types\IO\Red4Reader.cs:line 227
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\RedPackageReader.cs:line 51
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadChunk(RedPackageChunkHeader c) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\RedPackageReader.File.cs:line 206
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\RedPackageReader.File.cs:line 121
   at WolvenKit.RED4.Archive.IO.entEntityTemplateReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\entEntityTemplateReader.cs:line 24
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\CR2WReader.File.cs:line 338
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.Archive\IO\CR2WReader.File.cs:line 179
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(Stream stream, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 68

```

**Comment by seberoth** [comment]
From the latest nightly (2023-02-25):

```
[26.02.2023 15:11:35] Message: Type "gameVisionModuleParams" is not known!
Source: WolvenKit.RED4
StackTrace:    at WolvenKit.RED4.IO.Red4Reader.CheckRedTypeInfos(List`1& redTypeInfos) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 625
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 39
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.File.cs:line 125
   at WolvenKit.RED4.Archive.IO.entEntityTemplateReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\entEntityTemplateReader.cs:line 18
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 329
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 171
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(BinaryReader br, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 101
[26.02.2023 15:11:35] Failed to read cr2w file C:\Users\seber\Documents\CP77Dev\Debug\source\archive\shard_a.ent
[26.02.2023 15:11:35] Unable to open file: C:\Users\seber\Documents\CP77Dev\Debug\source\archive\shard_a.ent
```

`gameVisionModuleParams` was removed in 1.5 I think, so there is no chance to open it with newer WolvenKit versions. Need to find the latest for 1.4

**Comment by manavortex** [comment]
How about adding a verbose error message for this case? E.g. "This file was created for an earlier game version and can no longer be read, try opening it with older versions of Wolvenkit <link to github release page>"?

**Comment by seberoth** [comment]
Because we don't know if its made for an earlier game version or someone just hex edited some values
