### ISSUE TITLE
Mesh/Ent: Preview stops updating after switching tabs

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1186]
Mesh/Ent preview only works for the first time when I switch to the tab. Afterwards, the preview won't update anymore.

https://user-images.githubusercontent.com/965785/222805335-6df77e99-2959-4660-9d6d-40b5b8dd2a75.mp4

Nightly 03-03 - this used to be working at the time of https://github.com/WolvenKit/WolvenKit/pull/1141 

Exception that's probably the reason when switching away from preview tab and back to it:

```C#
PropertyBinderImplementation: view.hxContentVisual.ItemsSource Binding received an Exception! - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: SceneNode already attach to a different node
   at HelixToolkit.SharpDX.Core.Model.Scene.GroupNodeBase.AddChildNode(SceneNode node)
   at HelixToolkit.Wpf.SharpDX.CompositeModel3D.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at HelixToolkit.Wpf.SharpDX.ItemsModel3D.ItemsSourceChanged(DependencyPropertyChangedEventArgs e)
   at HelixToolkit.Wpf.SharpDX.ItemsModel3D.<>c.<.cctor>b__19_0(DependencyObject s, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkContentElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at HelixToolkit.Wpf.SharpDX.ItemsModel3D.set_ItemsSource(IEnumerable value)
   at InvokeStub_ItemsModel3D.set_ItemsSource(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by seberoth** [comment]
Fixed with #1216
