### ISSUE TITLE
WKit  sometimes crashes when opening file…?

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1224]
Nightly 2023-03-15

![image](https://user-images.githubusercontent.com/965785/225760492-ac39d8b5-8936-4177-9d5d-6241a6f33567.png)

I clicked on the blue arrow in my custom mesh to look up a material property of metal_base.remt, and WKit flatlined. This is the last message in my error log: 

```
2023-03-16 22:49:11.680 [ERR] Unhandled exception in WolvenKit v8.8.2.0
2023-03-16 22:49:11.683 [ERR] Message: Unable to find the specified file.
Source: WolvenKit.App
StackTrace:    at WolvenKit.App.Models.FileModel..ctor(String path, Cp77Project project) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Models\FileModel.cs:line 21
   at WolvenKit.App.Services.WatcherService.<>c__DisplayClass23_0.<DetectProjectFiles>b__1(String _) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 130
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at DynamicData.Cache.Internal.CacheUpdater`2.AddOrUpdate(IEnumerable`1 items) in /_/src/DynamicData/Cache/Internal/CacheUpdater.cs:line 60
   at WolvenKit.App.Services.WatcherService.<>c__DisplayClass23_0.<DetectProjectFiles>b__0(ISourceUpdater`2 innerList) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 130
   at DynamicData.Cache.Internal.ReaderWriter`2.DoUpdate(Action`1 updateAction, Action`1 previewHandler, Boolean collectChanges) in /_/src/DynamicData/Cache/Internal/ReaderWriter.cs:line 184
   at DynamicData.Cache.Internal.ReaderWriter`2.Write(Action`1 updateAction, Action`1 previewHandler, Boolean collectChanges) in /_/src/DynamicData/Cache/Internal/ReaderWriter.cs:line 141
   at DynamicData.ObservableCache`2.UpdateFromSource(Action`1 updateAction) in /_/src/DynamicData/Cache/ObservableCache.cs:line 212
   at DynamicData.SourceCache`2.Edit(Action`1 updateAction) in /_/src/DynamicData/Cache/SourceCache.cs:line 59
   at WolvenKit.App.Services.WatcherService.DetectProjectFiles(Cp77Project proj) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 127
   at WolvenKit.App.Services.WatcherService.<>c__DisplayClass22_0.<RefreshAsync>b__0() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 120
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WolvenKit.App.Services.WatcherService.RefreshAsync(Cp77Project proj) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 120
   at WolvenKit.App.Services.WatcherService.OnTimer(Object state) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\WatcherService.cs:line 56
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

After starting it up again, I could open the file without problems - but I'm experiencing semi-frequent crashes during my workflow (<2/hr, but still). I've only noticed it in the last 3 days (since the 13th), but maybe I haven't been doing enough (I've been pretty lazy).

Sorry that I can't give a better bug description!

**Comment by seberoth** [comment]
Should be fixed with e0232c0
