### ISSUE TITLE
.anims export: No rig found for player anims / exception

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1309]
**Describe the bug**
With player anims, the export fails with "no rig found". 

**To Reproduce**
1. Add e.g. `base\animations\weapon\firearms\shotgun\constitutional_tactician\pwa_w_shotgun__constitutional_arms_tactician.anims` to your project
2. Export it via the export tool (or try to)

Nightly 2023-06-15:
```
[17/06/2023 15:27:34] Added game file to project: base\animations\weapon\firearms\shotgun\constitutional_tactician\pwa_w_shotgun__constitutional_arms_tactician.anims
[17/06/2023 15:27:38] No rig found
[17/06/2023 15:27:38] The following items failed:
F:\bla\source\archive\base\animations\weapon\firearms\shotgun\constitutional_tactician\pwa_w_shotgun__constitutional_arms_tactician.anims
```

Nightly 2023-06-17:
```
[17/06/2023 15:31:48] base\animations\weapon\firearms\shotgun\constitutional_tactician\pwa_w_shotgun__constitutional_arms_tactician.anims - Object reference not set to an instance of an object.
[17/06/2023 15:31:48] Message: Object reference not set to an instance of an object.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.Animation.CompressedBuffer.AddAnimation(ModelRoot& model, animAnimation animAnimDes, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\Animation\AnimSpline.cs:line 40
   at WolvenKit.Modkit.RED4.ModTools.GetAnimation(CR2WFile animsFile, CR2WFile rigFile, ModelRoot& model, Boolean includeRig, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 360
   at WolvenKit.Modkit.RED4.ModTools.ExportAnim(CR2WFile animsFile, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 66
   at WolvenKit.Modkit.RED4.ModTools.ExportAnim(Stream animStream, List`1 archives, FileInfo outfile, Boolean isGLBinary, Boolean incRootMotion) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\AnimationTools.cs:line 25
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 469
[17/06/2023 15:31:48] The following items failed:
F:\bla\source\archive\base\animations\weapon\firearms\shotgun\constitutional_tactician\pwa_w_shotgun__constitutional_arms_tactician.anims
```

**Comment by seberoth** [comment]
Fixed with 98094e6
