### ISSUE TITLE
Safe handle has been closed error during export via wscript 

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/WolvenKit#1311]
**Describe the bug**
whilst running the vehicle export script on the arch bike (v_sportbike2_arch_nemesis_basic_01.ent) I'm getting this on the wkit console:
[19/06/2023 21:21:48] base\vehicles\sportbike\v_sportbike2_arch_nemesis\entities\meshes\v_sportbike2_arch_nemesis__ext01_axle_f_a_01.mesh - Safe handle has been closed.
Object name: 'SafeHandle'.
[19/06/2023 21:21:48] Message: Safe handle has been closed.
Object name: 'SafeHandle'.
Source: System.Private.CoreLib
StackTrace:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at Interop.Kernel32.MapViewOfFile(SafeMemoryMappedFileHandle hFileMappingObject, Int32 dwDesiredAccess, Int32 dwFileOffsetHigh, Int32 dwFileOffsetLow, UIntPtr dwNumberOfBytesToMap)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at WolvenKit.RED4.Archive.Archive.CopyFileSegmentToStream(Stream outStream, FileSegment offsetEntry, Boolean decompress) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\Base\Archive.cs:line 204
   at WolvenKit.RED4.Archive.Archive.CopyFileToStream(Stream stream, UInt64 hash, Boolean decompressBuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\Base\Archive.cs:line 122
   at WolvenKit.Modkit.RED4.ModTools.InternalTryFindFile(List`1 archives, UInt64 hash, FindFileEntry& result, Boolean excludeCustomArchives) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\ModTools.Helper.cs:line 101
   at WolvenKit.Modkit.RED4.ModTools.TryFindFile(List`1 archives, ResourcePath path, FindFileEntry& result, Boolean excludeCustomArchives) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\ModTools.Helper.cs:line 38
   at WolvenKit.Modkit.RED4.ModTools.GetMaterialEntries(CR2WFile cr2w, Stream meshStream, List`1& primaryDependencies, List`1& materialEntryNames, List`1& materialEntries, List`1 archives) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 255
   at WolvenKit.Modkit.RED4.ModTools.ParseMaterials(CR2WFile cr2w, Stream meshStream, FileInfo outfile, List`1 archives, String matRepo, MeshesInfo info, EUncookExtension eUncookExtension) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 597
   at WolvenKit.Modkit.RED4.ModTools.ExportMesh(Stream meshStream, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 867
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(Stream cr2wStream, FileInfo cr2wFileName, MeshExportArgs meshargs) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 878
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 441

**To Reproduce**
1.  Add v_sportbike2_arch_nemesis_basic_01.ent to a project
2. Run the wscript from https://wiki.redmodding.org/wolvenkit/modding-community/exporting-to-blender/exporting-vehicles
3. See error

**Expected behavior**
should just export a bunch of stuff.

**Version (please complete the following information):**
 - 18-6-23 Nightly

**Comment by seberoth** [comment]
Known issue :( Can also happens on bulk extracting stuff

**Comment by Simarilius-uk** [comment]
ah ok, not one I'd come across before.

**Comment by seberoth** [comment]
Should be fixed with 546a0c3
