### ISSUE TITLE
Importing only materials.json fail 

### ISSUE THREAD

**Issue by BeDuw** [WolvenKit/WolvenKit#1314]
Failing to import the materials.json file back into mesh after adding a brand new material entry. Log gets me the next error:
![image](https://github.com/WolvenKit/WolvenKit/assets/100306206/ab7eaebf-e802-44d9-b91c-7ff617cb9e8b)

Tried importing the same file using an 8.7 build and it imports just fine. 

A bit more context:
https://discord.com/channels/717692382849663036/808086068023918603/1122305451455942807

**Comment by manavortex** [comment]
Can reproduce this when trying to import material.json over a different mesh:


```
[06/07/2023 19:47:18] The following items failed:
F:\CyberpunkFiles\weapons\lightsabers\source\raw\manavortex\weapons\melee\lightsaber\w_lightsaber.glb
[06/07/2023 19:47:32] Message: Specified method is not supported.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.<GetMaterialParameterValue>g__ReadPath|56_0[T](<>c__DisplayClass56_0&) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 985
   at WolvenKit.Modkit.RED4.ModTools.GetMaterialParameterValue(Type materialParameterType, Object obj) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 941
   at WolvenKit.Modkit.RED4.ModTools.WriteMatToMesh(CR2WFile& cr2w, String _matData, List`1 archives) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 1322
   at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inMeshStream, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 304
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 487
[06/07/2023 19:47:32] The following items failed:
F:\CyberpunkFiles\weapons\lightsabers\source\raw\manavortex\weapons\melee\lightsaber\w_lightsaber.glb
```
Project attached, just in case you need it.
[lightsabers.zip](https://github.com/WolvenKit/WolvenKit/files/11970808/lightsabers.zip)

**Comment by seberoth** [comment]
Actually not the same cause.

BeDuws problem was solved on Discord (set a value to `null` instead of "0").
Your problem is caused by the new json format. Will fix it later
