### ISSUE TITLE
GLB import fails with Value was either too large or too small for an Int16

### ISSUE THREAD

**Issue by gewfsmc** [WolvenKit/WolvenKit#1361]
Hi,

When importing GLB I get this error:
```
Message: Value was either too large or too small for an Int16.
Source: System.Private.CoreLib
StackTrace:    at System.Convert.ThrowInt16OverflowException()
   at System.Convert.ToInt16(Int32 value)
   at WolvenKit.Modkit.RED4.ModTools.RawMeshToRE4Mesh(RawMeshContainer mesh, Vector4 qScale, Vector4 qTrans) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 693
   at WolvenKit.Modkit.RED4.ModTools.<>c__DisplayClass67_0.<ImportMesh>b__1(RawMeshContainer _) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 445
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inMeshStream, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MeshImportTools.cs:line 481
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Import.cs:line 487
```

mesh has weights, is triangulated and has UV. Mesh can be found: [Mesh](https://www.file.io/niPR/download/W3IYfEeYb1kS)

**Comment by effs** [comment]
This is a float/double precision problem in quantization, values at or very close to min or max extents can go out of range by a very small amount because floating point math.

The quick and probably correct fix is to clamp the conversions (the precision loss is < 0.1 mm, need to write it down exactly), but it's possible at least some cases we could alternatively compute with double precision instead, or explicitly rely on an epsilon.

(OP's file is now fixed but the problem itself remains.)
