### ISSUE TITLE
Getting a error on Wolvenkit 0.6.1.0 when trying to extract .redswf

### ISSUE THREAD

**Issue by Snake3y3s** [WolvenKit/WolvenKit#1373]
I am using a older version of Wolvenkit to try extract a .redswf from The Witcher (v1.32) to make a comparison with a modded version to see what has changed so that I can make the same changes in the nextgen version.

Getting the following error

at Ionic.Zlib.InflateManager.Inflate(FlushType flush)
   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at WolvenKit.Bundles.BundleItem.Extract(Stream output) in C:\DATA\GitHub\Traderain\Wolven-kit\WolvenKit.Bundles\BundleItem.cs:line 101
   at WolvenKit.Bundles.BundleItem.Extract(BundleFileExtractArgs e) in C:\DATA\GitHub\Traderain\Wolven-kit\WolvenKit.Bundles\BundleItem.cs:line 110
   at WolvenKit.frmMain.AddToMod(WitcherListViewItem item, Boolean skipping, List`1 managers, Boolean AddAsDLC) in C:\DATA\GitHub\Traderain\Wolven-kit\WolvenKit\Forms\frmMain.cs:line 1087

**Comment by seberoth** [comment]
Please report to [WolvenKit-7](https://github.com/WolvenKit/WolvenKit-7)
