### ISSUE TITLE
Phantom liberty. Error: Type "physicsMaterialTagProjectileRicochet" is not known!

### ISSUE THREAD

**Issue by Selectorrr** [WolvenKit/WolvenKit#1374]
**Describe the bug**
Importing game assets fails with an error when creating a project

```
[26.09.2023 12:41:20] [Error    ] Message: Type "physicsMaterialTagProjectileRicochet" is not known!
Source: WolvenKit.RED4
StackTrace:    at WolvenKit.RED4.IO.Red4Reader.CheckRedTypeInfos(List`1& redTypeInfos) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 643
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadVariable(RedBaseClass cls) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 173
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 46
   at WolvenKit.RED4.IO.Red4Reader.ReadClass(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 122
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadVariable(RedBaseClass cls) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 173
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 46
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadChunk(Int32 chunkIndex) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 240
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 123
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(Stream stream, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 74
```

**To Reproduce**
1. Install phantom liberty
2. Create new project

**Expected behavior**
Then new project will open without error

**Version (please complete the following information):**
 - Version 8.10.0

**Screenshots**
<img width="1270" alt="Снимок экрана 2023-09-26 в 12 48 41" src="https://github.com/WolvenKit/WolvenKit/assets/973663/b793feb1-960c-48c8-aca4-fe7f2adc8ede">

**Comment by seberoth** [comment]
Please wait for the WolvenKit update...
#1369

**Comment by ddzirt** [comment]
I have the same issue on clean Cyberpunk 2077 install without Phantom Liberty DLC installed or even bought for that matter. Also same clean Wolven kit install and all the latest plugins.

**Comment by seberoth** [comment]
There is no release yet for WolvenKit with 2.0 support

Please use the nightly build
https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/latest

**Comment by ddzirt** [comment]
Thanks!
