### ISSUE TITLE
Very slow saving and freezing when editing .app files

### ISSUE THREAD

**Issue by jhamilton0** [WolvenKit/WolvenKit#1383]
**Describe the bug**
In the WolvenKit-8.11.0-nightly.2023-09-27 build, It can take up to several minutes to save many appearance files, and trying to save a few like citizen_nightlife_wa.app will cause the program to freeze and never finish saving.  In previous versions of WolvenKit, saving these files could be a bit slow, but was far faster than in the current build, and always finished reliably.

**To Reproduce**
1. add the file base\characters\appearances\citizen\backup\citizen__nightlife_wa.app
2. make an edit and attempt save the modified .app file

**Comment by jhamilton0** [comment]
After waiting around a half hour for citizen__nightlife_wa.app, WolvenKit eventually unfroze and returned the following error:

[10/1/2023 10:36:23 PM] [Error    ] Error while saving D:\Modding\Cyberpunk_2077_Modding\source\archive\base\characters\appearances\citizen\citizen__nightlife_wa.app
[10/1/2023 10:36:23 PM] [Error    ] Message: Exception of type 'System.OutOfMemoryException' was thrown.
Source: System.Text.Json
StackTrace:    at System.Text.Json.JsonReaderHelper.TranscodeHelper(ReadOnlySpan`1 utf8Unescaped)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at WolvenKit.RED4.CR2W.JSON.RedJsonSerializer.Serialize(Object value, RedJsonSerializerOptions redOptions) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\CR2W\JSON\RedJsonSerializer.cs:line 135
   at WolvenKit.App.Services.AppScriptService.OnSaveHook(String filePath, CR2WFile& cr2wFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\AppScriptService.Hook.cs:line 75
   at WolvenKit.App.Services.AppHookService.OnSave(String extStr, CR2WFile& cr2wFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\AppHookService.cs:line 12
   at WolvenKit.App.ViewModels.Documents.RedDocumentViewModel.Save(Object parameter) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Documents\RedDocumentViewModel.cs:line 169
