### ISSUE TITLE
HttpClient timeout when downloading Wolvenkit Resources 

### ISSUE THREAD

**Issue by T0uchM3** [WolvenKit/WolvenKit#1398]
Error message:
Unhandled exception in WolvenKit v8.11.0.0
Message: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Source: System.Net.Http
StackTrace:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at WolvenKit.App.Services.PluginService.InstallPluginAsync(EPlugin id) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Services\PluginService.cs:line 303
   at WolvenKit.App.ViewModels.HomePage.Pages.PluginViewModel.Install() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\HomePage\Pages\PluginViewModel.cs:line 136
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rfuzzo** [comment]
cannot reproduce. checked with wkit-resources which installed correctly.

**Comment by Sandkorndieb** [comment]
Same. WolvenKit-8.17.2-nightly.2025-11-23, during Plugin install WK Resources.
[Log.txt](https://github.com/user-attachments/files/23698456/Log.txt)
