### ISSUE TITLE
Saved but unmodified appearance files in 8.11.0 cause stacktrace in Nightly

### ISSUE THREAD

**Issue by mnh86** [WolvenKit/WolvenKit#1400]
**Describe the bug**
The following .app files saved with 8.11.0 stable were unable to be opened for edit in 8.11.1-nightly.2023-10-18
- `base\characters\appearances\service\service__sexworker_wa.app`
- `ep1\characters\appearances\service\service__sexworker_wa.app`

Seeing WolvenKit.RED4 StackTrace in 8.11.1-nightly.2023-10-18
```
[10/20/2023 9:45:33 AM] [Error    ] Message: Exception of type 'System.Exception' was thrown.
Source: WolvenKit.RED4
StackTrace:    at WolvenKit.RED4.IO.Red4Reader.GetStringValue(UInt16 index, Boolean isTypeInfo) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 60
   at WolvenKit.RED4.Types.worldCompiledEffectInfo.CustomRead(Red4Reader reader, UInt32 size, CName propertyName) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\ClassesExt\CustomData\worldCompiledEffectInfo.cs:line 35
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 143
   at WolvenKit.RED4.IO.Red4Reader.ReadClass(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 122
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 143
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.File.cs:line 129
   at WolvenKit.RED4.Archive.IO.appearanceAppearanceDefinitionReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\appearanceAppearanceDefinitionReader.cs:line 20
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 301
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 149
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(BinaryReader br, Boolean parseBuffers, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 112
[10/20/2023 9:45:33 AM] [Error    ] Failed to read cr2w file G:\Modding\Cyberpunk\BugTests\source\archive\base\characters\appearances\service\service__sexworker_wa.app
[10/20/2023 9:45:33 AM] [Warning  ] Unable to open file: G:\Modding\Cyberpunk\BugTests\source\archive\base\characters\appearances\service\service__sexworker_wa.app
```

**To Reproduce**
1. Open WolvenKit 8.11.0, and create a new project. Include the above .app files into the project. Open them and click save on each.
2. Then open WolvenKit 8.11.1-nightly.2023-10-18, and attempt to open the .app files.
3. See above stacktrace error

**Expected behavior**
The files should open without error.

**Comment by seberoth** [comment]
Same reason why the game crashes for unmodified ents with 8.11 (#1399)
Stable writes wrong data, need to redo it with nightly

**Comment by mnh86** [comment]
Thanks. Just to confirm my understanding - for modified .app/.ent files that had used stable, those changes will need to be redone by the user when using nightlies/next stable release? Or would a future release perform a conversion to migrate to fixed data? Just trying to gauge how much duplicate work I may need to plan for.

**Comment by mnh86** [comment]
And if user will need to redo modifications, are there any tricks they could do to export/import somehow from old to new format (I'm new and not familiar with all the features)?

This is what I'm considering based on my current knowledge:
1. Export the modified bad data files to JSON and the corresponding original game files (using 8.11 stable)
2. Diff the JSON files orig -> modified to get a delta of the changes
3. Use the delta as reference to make the manual changes again using nightly

**Comment by seberoth** [comment]
Yeah, that procedue should work. We can't fix already borked files, since I forgot to read some parts and if you saved them again, these would not getting written at all. So they are not in the file anymore now

**Comment by mnh86** [comment]
No worries! I understand the risk of being on the bleeding edge of the 2.0+ changes. I used above procedure and got my changes into the new format. Thank you for your work!
