### ISSUE TITLE
Regression: Can't copy component to file with latest Nightly

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1409]
**Version**
Nightly 30-10-2023

[source - Copy.zip](https://github.com/WolvenKit/WolvenKit/files/13207027/source.-.Copy.zip)

**To Reproduce**
1. Open `tutorial\npv\your_female_character\ops\npv_pm.app` from attached source folder
2. From the first appearance definition, copy the `PhotomodeAnimations` component
3. Open `tutorial\npv\your_female_character\ops\your_female_character.app`
4. Paste the component to the component array of the second appearance definition (`business`)
5. Delete the already existing `PhotomodeAnimations`
6. Save the .app
7. There will now be an exception:

```
\npv\your_female_character\ops\your_female_character.app
[30/10/2023 16:35:03] [Error    ] Unhandled exception in WolvenKit v8.11.1.0
[30/10/2023 16:35:03] [Error    ] Message: Could not find a part of the path 'C:\01_apps\WolvenKit_Nightly\tutorial\npv\your_female_character\ops\your_female_character.tmp'.
Source: System.Private.CoreLib
StackTrace:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at WolvenKit.App.ViewModels.Documents.RedDocumentViewModel.Save(Object parameter) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Documents\RedDocumentViewModel.cs:line 154
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

It works in the version before (which is how the component got into the first appearance definition). This time, I triple-checked.

**Comment by cgmartin** [comment]
I am also seeing this error in Nightly 30-10-2023

**Comment by rfuzzo** [comment]
ah I know what it is 🤔 That's on me
