### ISSUE TITLE
Mesh export: Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1428]
When trying to export my mesh (see zip file), I get the following exception. I didn't do anything fishy and they import just fine, only exporting doesn't work: 
[broken_mesh.zip](https://github.com/WolvenKit/WolvenKit/files/13327930/broken_mesh.zip)

```
[12/11/2023 13:10:45] [Error    ] relative\path\in\project\ash.mesh - Unable to read beyond the end of the stream.
[12/11/2023 13:10:45] [Error    ] Message: Unable to read beyond the end of the stream.
Source: System.Private.CoreLib
StackTrace:    at System.IO.BinaryReader.ReadByte()
   at WolvenKit.Modkit.RED4.Tools.MeshTools.WriteGarmentParametersToMesh(List`1& meshes, CMesh cMesh, Boolean exportGarmentSupport) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 1448
   at WolvenKit.Modkit.RED4.Tools.MeshTools.GetModel(CR2WFile cr2w, Boolean lodFilter, Boolean includeRig, UInt64 chunkMask, Boolean mergeMeshes, Boolean exportGarmentSupport) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 84
   at WolvenKit.Modkit.RED4.Tools.MeshTools.ExportMesh(CR2WFile cr2w, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vMode) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Tools\MeshTools.cs:line 34
   at WolvenKit.Modkit.RED4.ModTools.ExportMesh(Stream meshStream, FileInfo outfile, MeshExportArgs meshExportArgs, ValidationMode vmode) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Uncook.cs:line 872
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(Stream cr2wStream, FileInfo cr2wFileName, MeshExportArgs meshargs) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Uncook.cs:line 880
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Uncook.cs:line 445
[12/11/2023 13:10:45] [Error    ] The following items failed:
F:\CyberpunkFiles\project\source\archive\relative\path\in\project\ash.mesh
[12/11/2023 13:11:37] [Important] Using classic mesh exporter.
```

### How I got here
I've been porting meshes from .fbx files (they were all from the same .unitypackage), so I don't think it's anything about the fbx files. 
1. I exported a Cyberpunk head item
2. duplicated the submeshes
3. nuked the vertices
4. joined my repositioned FBX into the new empty submeshes
… then repeated steps 3 and 4 with every other fbx from the archive. 

Somehow, the very first of those still exports (the others don't, same error for all of them):
[this_one_works_for_some_reason.zip](https://github.com/WolvenKit/WolvenKit/files/13327950/this_one_works_for_some_reason.zip)

**Comment by effs** [comment]
Immediate problem is that the mesh only has garmentsupport for submesh_02, but it's trying to apply those to submesh_00.

Not sure whether this is because of import not creating the correct skippables for 00 and 01, or if the exporter is incorrectly not skipping them. Need to find some example cases where the data is correct.
