### ISSUE TITLE
Can't import .wav audio files back into project (Cyberpunk 2077)

### ISSUE THREAD

**Issue by Max-Pare** [WolvenKit/WolvenKit#1461]
**Describe the bug**
When trying to import .wav audio files, wolvenkit throws an exception with the following error:

```
[02/12/2023 20:03:45] [Error    ] Unhandled exception in WolvenKit v8.11.1.0
[02/12/2023 20:03:45] [Error    ] Message: The input string 'audio_file_name' was not in a correct format.
Source: System.Private.CoreLib
StackTrace:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Convert.ToUInt32(String value)
   at WolvenKit.Modkit.RED4.Opus.OpusTools.<>c.<ImportWavs>b__11_0(String wav) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\OpusTools.cs:line 146
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WolvenKit.Modkit.RED4.Opus.OpusTools.ImportWavs(String[] wavFiles) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\OpusTools.cs:line 146
   at WolvenKit.App.ViewModels.Importers.ImportViewModel.<>c__DisplayClass12_0.<ImportWavs>b__0() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\ImportViewModel.cs:line 221
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WolvenKit.App.ViewModels.Importers.ImportViewModel.ExecuteProcessBulk(Boolean all) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Importers\ImportViewModel.cs:line 176
   at WolvenKit.App.ViewModels.Tools.ImportExportViewModel.ProcessAll() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\ImportExportViewModel.cs:line 56
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**To Reproduce**
1. Find any .wem file in the Asset Browser
2. Export the file to .wav
3. Try to import .wav file back into WolvenKit
4. Error occurs

**Expected behavior**
the .wav file should be imported as a .wem file to use in a mod.

**Version (please complete the following information):**
 - Version 8.11.1

**Comment by seberoth** [comment]
Not really a bug.

wav import is currently only implemented for opuspak files and there the name needs to be the id of the sound to replace.
wav to wem isn't implemented at all.

Would need to:
 - Implement wav to wem
 - Find a way to distinguish between wav -> opuspak and wav -> wem

**Comment by rfuzzo** [comment]
Alright, I removed the bug label
