### ISSUE TITLE
Can't export edited .morphtargets

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1463]
**Describe the bug**

As soon as I import .glb data into a .morphtarget file, I can't ever export the file again:

```
[03/12/2023 17:52:48] [Error    ] Failed to export hx_000_pma__morphs_cyberware_02.morphtarget: Accessor[7] JOINTS_0[0]: Is out of bounds
[03/12/2023 17:52:48] [Debug    ] SharpGLTF.Validation.DataException: Accessor[7] JOINTS_0[0]: Is out of bounds
   at SharpGLTF.Validation.ValidationContext._DataThrow(ValueLocation pname, String msg)
   at SharpGLTF.Validation.ValidationContext.AreJoints(ValueLocation pname, IList`1 joints, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.Accessor._ValidateJoints(ValidationContext validate, String attributeName, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.Accessor.ValidateVertexAttributes(ValidationContext validate, IReadOnlyDictionary`2 attributes, Int32 skinsMaxJointCount)
   at SharpGLTF.Schema2.MeshPrimitive.OnValidateContent(ValidationContext validate)
   at SharpGLTF.IO.JsonSerializable.ValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.Mesh.OnValidateContent(ValidationContext validate)
   at SharpGLTF.IO.JsonSerializable.ValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ModelRoot.OnValidateContent(ValidationContext validate)
   at SharpGLTF.IO.JsonSerializable.ValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.WriteContext._ValidateBeforeWriting(ModelRoot model)
   at SharpGLTF.Schema2.WriteContext.WriteBinarySchema2(String baseName, ModelRoot model)
   at SharpGLTF.Schema2.ModelRoot.SaveGLB(String filePath, WriteSettings settings)
   at WolvenKit.Modkit.RED4.ModTools.ExportMorphTargets(Stream targetStream, FileInfo outfile, List`1 archives, String modFolder, Boolean isGLBinary, ValidationMode vMode) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Tools\MorphTargetTools.cs:line 98
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Uncook.cs:line 468
   at WolvenKit.Modkit.RED4.ModTools.Export(FileInfo cr2wFile, GlobalExportArgs args, DirectoryInfo basedir, DirectoryInfo rawOutDir, ECookedFileFormat[] forceBuffers) in C:\Users\manav\Documents\01_coding\Wolvenkit\WolvenKit.Modkit\RED4\Export.cs:line 61
[03/12/2023 17:52:48] [Error    ] The following items failed:
F:\CyberpunkFiles\commissions\React\e3_cyberware_for_V_slot_02\source\archive\base\characters\head\player_base_heads\player_man_average\hx_000_pma__morphs_cyberware_02.morphtarget
```

On top of that, if I import into a morphtarget twice, there will be clipping. 

How to reproduce:
- grab pwa basehead morphtarget and .mesh, then any other morphtarget and mesh (e.g. cyberware_2) from the character creation options
- export all of it
- import both .morphtargets into Blender
- Nuke vertex data from the head, maybe keep a few faces for funsies. 
- Join the other mesh data into the empty mesh.
- Export into head .mesh and morphtarget
- import head mesh into Wkit
- import head morphtarget into WKit
- rename head morphtarget and .mesh to the other one (e.g. cyberware_2)
- re-path morphtarget to point at the correct mesh
At this point, everything will work in-game, I have a moving morphtarget and everything works fine.
I'm observing two errors here:
- Export the re-named .morphtarget file will throw the exception stated above
On top of that, importing into the re-named morphtargets will not work:
- From Blender, export the same mesh that you previously used (or replace the cyberware .glb files with the head ones? I didn't try that, but I'd expect that to be broken as well)
- Import these files into the re-named .mesh and .morphtarget (cyberware_02)
- Although the data is identical, the mesh will now clip in-game

**Comment by effs** [comment]
Just export-import-export works fine for my `.morphtarget`s

1. Does the problem occur if you rename the files to the correct targets before importing them?
2. Does the problem occur in current main?
3. Does the problem occur in 2023-11-29 nightly?

If yes, can you send me the once-exported `.mesh` and `.morphtarget`? I suspect this has something to do with changing it from `h0` to `hx` without fully basing it on `hx`.

**Comment by manavortex** [comment]
hey, sure, I'll send you more files tonight :3 If you haven't seen anything in 14 hours, please poke me with a stick

**Comment by manavortex** [comment]
Hey, 
I've done extensive testing and was unable to reproduce the error under 3.6.1 with plugin version 1.5.1. Stands to reason that the error is somehow related to Blender 4, I'll report back if I run into it again. Below are my test cases:

source files:
base\characters\head\player_base_heads\player_female_average\h0_000_pwa__morphs.morphtarget
base\characters\head\player_base_heads\player_female_average\h0_000_pwa_c__basehead\h0_000_pwa_c__basehead.mesh

target files: 
base\characters\head\player_base_heads\player_female_average\hx_000_pwa__morphs_cyberware_02.morphtarget
base\characters\head\player_base_heads\player_female_average\h0_000_pwa_c__basehead\hx_000_pwa_c__basehead_cyberware_02.mesh

case 1: works and does not clip
1. export: basehead mesh&morphtarget
2. import: basehead mesh
3. import: basehead morphtarget
4. change file names to cyberware_02
5. change mesh file path & default texture in morphtarget
6. copied materials from original mesh

case 2: works and does not clip
1. export: basehead mesh&morphtarget
2. change file names to cyberware_02
3. import: basehead mesh (same .glb file as in case 1, but renamed)
4. import: basehead morphtarget (same .glb file as in case 1, but renamed)
5. change mesh file path & default texture in morphtarget
6. copied materials from original mesh

case 3: works and does not clip
1. change file names to cyberware_02
2. export: cyberware_02 mesh&morphtarget
3. import: cyberware_02 mesh (blender export into existing file, identical data)
4. import: cyberware_02 morphtarget (blender export into existing file, identical data)
5. change mesh file path & default texture in morphtarget
6. copied materials from original mesh

case 4: works and does not clip
1. change file names to cyberware_02
2. change mesh file path & default texture in morphtarget
3. copied materials from original mesh
4. import: cyberware_02 mesh (same files as in case 3)
4. import: cyberware_02 morphtarget (same files as in case 3)
 
case 5: works and does not clip (kinda)
1. change file names to cyberware_02
2. change mesh file path & default texture in morphtarget
3. copied materials from original mesh
4. export mesh and morphtarget
result: morphtarget exception
```
hx_000_pwa__morphs_cyberware_02.morphtarget: Accessor[7] JOINTS_0[0]: Is out of bounds
[09/12/2023 15:31:11] [Error    ] The following items failed:
F:\CyberpunkFiles\commissions\React\e3_cyberware_for_V_slot_02\source\archive\base\characters\head\player_base_heads\player_female_average\hx_000_pwa__morphs_cyberware_02.morphtarget
```

Even importing and re-exporting the cropped morphtarget-mesh into Blender didn't make it clip. It's probably something to do with Blender4?

**Comment by DoctorPresto** [comment]
Are you using 1.5.1? I'm not sure if the blender 4 export fixes made it into 1.5.1. could you try with the current dev version and let me know if it's still an issue?

**Comment by manavortex** [comment]
The tests above were with 1.5.1, and at least the 

> Are you using 1.5.1? I'm not sure if the blender 4 export fixes made it into 1.5.1. could you try with the current dev version and let me know if it's still an issue?

The tests above were all with 1.5.1 and Blender 3.6. I'll do another round the moment I scrape up a spoon.

**Comment by Berdagon** [comment]
I do have a similar problem with 1.5.1 and Blender 4.0 when: 
1- export player base body: base\characters\common\player_base_bodies\player_female_average\t0_000_pwa_base__full.morphtarget
2 - import it to blender 
3 - export it without any changes to that same morphtarget file
4 - try to import it again in Wolvenkit and receive "[12/14/2023 1:18:41 PM] [Error    ] Message: Accessor[11] _bufferView: must be defined." error

**Comment by seberoth** [comment]
@Berdagon 

Thats another issue we can't currently fix. But it will be "fixed" in the next blender addon release

**Comment by Revonlieke** [comment]
Was this ever fixed cause I keep getting the same error?

**Comment by manavortex** [comment]
Yeah, you "just" need to use the right versions of WKit and the plugin

**Comment by Revonlieke** [comment]
Coolio, I am using both latest+latest blender. Issue was I did not tick wkit recommended export settings.
