### ISSUE TITLE
Unable to add "compiledData" to C2dArray csv

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#1480]
**Describe the bug**
When I try to add or create an item in the "compiledData" header of the C2dArray file I get this error:

```
[18/12/2023 11:44:22] [Error    ] Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source: System.Private.CoreLib
StackTrace:    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at WolvenKit.RED4.Types.CArrayBase`1.System.Collections.IList.get_Item(Int32 index) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\Primitives\CArrayBase.cs:line 161
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.CalculateDescriptor() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 1938
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel..ctor(IRedType data, String name, AppViewModel appViewModel, IChunkViewmodelFactory chunkViewmodelFactory, IDocumentTabViewmodelFactory tabViewmodelFactory, IHashService hashService, ILoggerService loggerService, IProjectManager projectManager, IGameControllerFactory gameController, ISettingsManager settingsManager, IArchiveManager archiveManager, ITweakDBService tweakDbService, ILocKeyService locKeyService, Red4ParserService parserService, ChunkViewModel parent, Boolean isReadOnly) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 134
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.CalculateProperties() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2126
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.RecalculateProperties(IRedType selectChild) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2707
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.InsertChild(Int32 index, IRedType item) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2693
```
It creates a REDdummy entry with index "-1". Opening this file gives the error:
```
[18/12/2023 11:51:35] [Error    ] Unhandled exception in WolvenKit v8.11.2.0
[18/12/2023 11:51:35] [Error    ] Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source: System.ComponentModel.TypeConverter
StackTrace:    at System.ComponentModel.ReflectPropertyDescriptor.SetValue(Object component, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeViewCollectionHelper.SetValue(Object data, String propertyName, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeCollectionView.Nodes_PropertyChanged(TreeViewNode node, PropertyChangeNotificationSource notificationSource, PropertyChangedEventArgs e)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeQueryableCollectionView.Nodes_PropertyChanged(TreeViewNode node, PropertyChangeNotificationSource notificationSource, PropertyChangedEventArgs e)
   at Syncfusion.UI.Xaml.TreeView.SfTreeView.ExpandNode(TreeViewNode treeViewNode)
   at Syncfusion.UI.Xaml.TreeView.SelectionController.HandleTouchInteraction(SelectionTrigger gesture, TreeViewItemInfoBase itemInfo, Point position, Boolean isExpanderView)
   at Syncfusion.UI.Xaml.TreeView.TreeViewItem.ProcessTreeViewTouchEvents(Boolean isExpanderView, SelectionTrigger touchGesture, Point gestureRecognizer)
   at Syncfusion.UI.Xaml.TreeView.TreeViewItem.OnExpanderViewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Copying over the array from "data" works as a workaround for the time being.

**To Reproduce**
1. Create C2dArray (.csv) file
2. Click on "compiledData" header
3. Click on "Create item in array"

**Version (please complete the following information):**
 - Version [8.11.2-nightly.2023-12-16]

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/17293117/30cc3b7a-beb9-4637-a6d2-be8cb93bbb9b)
![image](https://github.com/WolvenKit/WolvenKit/assets/17293117/b0095b4e-37a1-48a1-8512-d855e22d7a69)

**Comment by manavortex** [comment]
I broke it, I'll fix it
