### ISSUE TITLE
streamingBlock additions don't work

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#1496]
**Describe the bug**

```
[04/01/2024 00:28:12] [Error    ] Message: Exception of type 'System.ArgumentNullException' was thrown. (Parameter 'wssd.Data.DepotPath.GetResolvedText()')
Source: WolvenKit.Core
StackTrace:    at WolvenKit.Core.Extensions.Ensure.NotNull[T](T obj, String message, String parameterName) in D:\a\WolvenKit\WolvenKit\WolvenKit.Core\Extensions\Ensure.cs:line 51
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.CalculateDescriptor() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 1977
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel..ctor(IRedType data, String name, AppViewModel appViewModel, IChunkViewmodelFactory chunkViewmodelFactory, IDocumentTabViewmodelFactory tabViewmodelFactory, IHashService hashService, ILoggerService loggerService, IProjectManager projectManager, IGameControllerFactory gameController, ISettingsManager settingsManager, IArchiveManager archiveManager, ITweakDBService tweakDbService, ILocKeyService locKeyService, Red4ParserService parserService, ChunkViewModel parent, Boolean isReadOnly) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 142
   at WolvenKit.App.Factories.ChunkViewmodelFactory.ChunkViewModel(IRedType rootChunk, String name, AppViewModel appViewModel, ChunkViewModel parent, Boolean isReadOnly) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Factories\ChunkViewmodelFactory.cs:line 59
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.CalculateProperties() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2240
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.RecalculateProperties(IRedType selectChild) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2764
   at WolvenKit.App.ViewModels.Shell.ChunkViewModel.InsertChild(Int32 index, IRedType item) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\ChunkViewModel.cs:line 2750
```

```
[04/01/2024 00:30:55] [Error    ] Unhandled exception in WolvenKit v8.12.0.0
[04/01/2024 00:30:55] [Error    ] Message: Exception of type 'System.ArgumentNullException' was thrown. (Parameter 'wssd.Data.DepotPath.GetResolvedText()')
Source: System.ComponentModel.TypeConverter
StackTrace:    at System.ComponentModel.ReflectPropertyDescriptor.SetValue(Object component, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.PropertyDescriptorExtensions.SetValue(PropertyDescriptorCollection propertyDescriptorCollection, Object record, Object value, String columnName)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeViewCollectionHelper.SetValue(Object data, String propertyName, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeCollectionView.Nodes_PropertyChanged(TreeViewNode node, PropertyChangeNotificationSource notificationSource, PropertyChangedEventArgs e)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeQueryableCollectionView.Nodes_PropertyChanged(TreeViewNode node, PropertyChangeNotificationSource notificationSource, PropertyChangedEventArgs e)
   at Syncfusion.UI.Xaml.TreeView.SfTreeView.ExpandNode(TreeViewNode treeViewNode)
   at Syncfusion.UI.Xaml.TreeView.SelectionController.ProcessExpanderInteraction(TreeViewNode treeViewNode, Boolean processselection)
   at Syncfusion.UI.Xaml.TreeView.SelectionController.HandleTouchInteraction(SelectionTrigger gesture, TreeViewItemInfoBase itemInfo, Point position, Boolean isExpanderView)
   at Syncfusion.UI.Xaml.TreeView.TreeViewItem.ProcessTreeViewTouchEvents(Boolean isExpanderView, SelectionTrigger touchGesture, Point gestureRecognizer)
   at Syncfusion.UI.Xaml.TreeView.TreeViewItem.OnExpanderViewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**To Reproduce**
1. Create a new streamingblock
2. Add an item to "descriptors", this will throw an error.
3. Save the streamingblock and re-open it
4. Will throw another error when opening the "descriptors" array

**Version (please complete the following information):**
 - Version [Since 8.9.0, still exists in 8.12.0]

**Screenshots**

**Comment by manavortex** [comment]
Hopefully fixed in https://github.com/WolvenKit/WolvenKit/pull/1495

**Comment by ArasakaApart** [comment]
Appears to be totally bonked in 01/06 nightly.
Can't import from json any longer and adding items to array just brings up a blank selection screen.

Nightly:
![image](https://github.com/WolvenKit/WolvenKit/assets/17293117/39fcf466-697d-43d7-a3b8-64a5ffaa0521)

**Comment by ArasakaApart** [comment]
Using Presto's files, editing a node still gives me an error.

```
[06/01/2024 14:43:44] [Error    ] Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source: System.ComponentModel.TypeConverter
StackTrace:    at System.ComponentModel.ReflectPropertyDescriptor.SetValue(Object component, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeViewCollectionHelper.SetValue(Object data, String propertyName, Object value)
   at Syncfusion.UI.Xaml.TreeView.Engine.TreeCollectionView.Nodes_PropertyChanged(TreeViewNode node, PropertyChangeNotificationSource notificationSource, PropertyChangedEventArgs e)
   at Syncfusion.UI.Xaml.TreeView.SfTreeView.ExpandNode(TreeViewNode treeViewNode)
   at Syncfusion.UI.Xaml.TreeView.SelectionController.ProcessExpanderInteraction(TreeViewNode treeViewNode, Boolean processselection)
   at Syncfusion.UI.Xaml.TreeView.SelectionController.HandleTouchInteraction(SelectionTrigger gesture, TreeViewItemInfoBase itemInfo, Point position, Boolean isExpanderView)
   at Syncfusion.UI.Xaml.TreeView.TreeViewItem.OnExpanderViewMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
This is on latest nightly, with your change.

**Comment by seberoth** [comment]
> brings up a blank selection screen
That another issue... Will open a ticket for that later
> Using Presto's files, editing a node still gives me an error.
Edited some stuff, worked fine. Would be nice if you could tell us what you are editing

**Comment by ArasakaApart** [comment]
Try saving the file and then opening it again after changing anything.
What I was doing is removing a node that shouldn't be there (duplicate none node under "nodes"). Saving the file then would cause the nodeData array to become corrupted and give the indexing error.
