### ISSUE TITLE
Deleting an array item causes Install / Pack unhandled exception

### ISSUE THREAD

**Issue by sammilucia** [WolvenKit/WolvenKit#1528]
**Describe the bug**
Deleting an array item from an env or envparam (and I would expect other files) saves the mod correctly, but packing and/or installing the mod fails with an unhandled exception

**To Reproduce**
1. Open an env file, e.g. `cp2077_master_env_ep1_v006.env`
2. Expand `worldRenderSettings` then `areaParameters`
3. Right-click `BlurAreaSettings` and select **Copy From Array/Buffer**
4. Open `24h_weather_sandstorm.envparam` and expand `worldRenderSettings` then `areaParameters`
5. Right-click `areaParameters` and select **Paste Into Array/Buffer**
6. (Notice `BlurAreaSettings` appears at the bottom)
7. Save and pack the mod
8. Right click `BlurAreaSettings` in `24h_weather_sandstorm.envparam` and select **Delete Item in Array/Buffer**
9. Save the mod (no error)
10. Pack or Install the mod, the following error is displayed:

```
[21 Jan 3:31:12 pm] [Error    ] Unhandled exception in WolvenKit v8.12.1.0
[21 Jan 3:31:12 pm] [Error    ] Message: Could not find a part of the path 'C:\Users\Samantha\Downloads\_modding\WolvenKit-nightly\base\weather\24h_basic\24h_weather_fog_new.tmp'.
Source: System.Private.CoreLib
StackTrace:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at WolvenKit.Helpers.FileHelper.SafeWrite(Stream stream, String outPath, ILoggerService logger) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Tools\FileHelper.cs:line 18
   at WolvenKit.App.ViewModels.Documents.RedDocumentViewModel.Save(Object parameter) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Documents\RedDocumentViewModel.cs:line 190
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

(Also tested: restoring the deleted items, the mod packs correctly again)

**Expected behavior**
Mod packs and installs correctly after the array is deleted.

**Version (please complete the following information):**
 - 8.12.1-nightly.2024-01-20+f7 (9? - last numbers clipped)) 
![image](https://github.com/WolvenKit/WolvenKit/assets/3295286/cd28eefe-dcc7-4fa2-9887-645ba9df8753)

**Comment by seberoth** [comment]
Followed your steps, but can't reproduce.
Also the error doesn't really makes sense in your scenario.

1. The error posted could only happen when you save a file, not on pack/install
2. It somehow seems like it tries to save a file which isn't part of your project. Not sure how that can happen.
3. Your steps involve `cp2077_master_env_ep1_v006.env` and `24h_weather_sandstorm.envparam`, but the error is about `24h_weather_fog_new.envparam`

**Comment by sammilucia** [comment]
yes i think you're right, the error was while saving. i'll test and confirm steps to repro. my impression was it was trying to save the files which i'ddeleted (and failing).

**Comment by sammilucia** [comment]
closing as i can't repro with latest nightly
