### ISSUE TITLE
Backwards compatibility: Wolvenkit fails to open old .ent file

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1538]
I found another file from an older game version that can't be open in the current WKit build. It's one of mine, so it has definitely not been fucked with, but it would be great if it could be made compatible (because other people will likely face the same problem).
[w_zarroc_mesh_entity.zip](https://github.com/WolvenKit/WolvenKit/files/14075488/w_zarroc_mesh_entity.zip)

```
[28/01/2024 10:17:59] [Warning  ] Unable to open file: F:\CyberpunkFiles\weapons\zarroc\source\archive\manavortex\weapons\melee\zarroc\w_zarroc_mesh_entity.ent
[28/01/2024 10:22:22] [Error    ] Message: Exception of type 'System.Exception' was thrown.
Source: WolvenKit.RED4
StackTrace:    at WolvenKit.RED4.IO.Red4Reader.GetStringValue(UInt16 index, Boolean isTypeInfo) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 62
   at WolvenKit.RED4.IO.Red4Reader.ReadCName() in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 190
   at WolvenKit.RED4.Types.worldCompiledEffectInfo.CustomRead(Red4Reader reader, UInt32 size, CName propertyName) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\ClassesExt\CustomData\worldCompiledEffectInfo.cs:line 35
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 85
   at WolvenKit.RED4.IO.Red4Reader.ReadClass(List`1 redTypeInfos, UInt32 size) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 139
   at WolvenKit.RED4.IO.Red4Reader.Read(List`1 redTypeInfos, UInt32 size) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 767
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 89
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadBuffer(RedBuffer buffer) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.File.cs:line 129
   at WolvenKit.RED4.Archive.IO.entEntityTemplateReader.ReadBuffer(RedBuffer buffer) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\entEntityTemplateReader.cs:line 18
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 296
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 149
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(Stream stream, CR2WFile& redFile) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 76
   ```

**Comment by seberoth** [comment]
1. In general, we don't have backwards compatibility
2. Your file is ineed corrupted, nothing to do with an old version (could be related to #1400)
