### ISSUE TITLE
Receiving constructor not found error when trying to open a modified inkwidget file(mod_settings_main.inkwidget)

### ISSUE THREAD

**Issue by Berdagon** [WolvenKit/WolvenKit#1541]
**Describe the bug**
Cant open the mod_settings_main.inkwidget file from mod_settings

**To Reproduce**
1. download the mod_settings mod(either from nexus or github)
2. add the base/gameplay/gui/fullscreen/settings/mod_settings_main.inkwidget to project
3. try to open it

**Expected behavior**
gives this error
`[1/30/2024 10:42:38 PM] [Error    ] Message: Constructor on type 'WolvenKit.RED4.Types.CHandle`1[[WolvenKit.RED4.Types.inkIWidgetController, WolvenKit.RED4, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null]]' not found.
Source: System.Private.CoreLib
StackTrace:    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at WolvenKit.RED4.IO.Red4Reader.ReadCHandle(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 424
   at WolvenKit.RED4.IO.Red4Reader.Read(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 819
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadVariable(RedBaseClass cls) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 129
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 54
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadChunk(Int32 chunkIndex) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 240
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 123
   at WolvenKit.RED4.Archive.IO.CR2WWrapperReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WWrapperReader.cs:line 30
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 296
   at WolvenKit.RED4.Archive.IO.CR2WReader.<ReadVariable>g__PostProcess|9_0(IRedType internalValue, <>c__DisplayClass9_0&) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 200
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadVariable(RedBaseClass cls) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 153
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 54
   at WolvenKit.RED4.IO.Red4Reader.ReadClass(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 139
   at WolvenKit.RED4.IO.Red4Reader.Read(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 767
   at WolvenKit.RED4.IO.Red4Reader.ReadCArray(List`1 redTypeInfos, UInt32 size, Boolean readAdditionalBytes) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 174
   at WolvenKit.RED4.IO.Red4Reader.Read(List`1 redTypeInfos, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Types\IO\Red4Reader.cs:line 769
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadVariable(RedBaseClass cls) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 129
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.cs:line 54
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadChunk(Int32 chunkIndex) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 240
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 123
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(BinaryReader br, Boolean parseBuffers, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 112
[1/30/2024 10:42:38 PM] [Error    ] Failed to read cr2w file D:\ProgramFiles\WolvenKit\Depot\checkfile\source\archive\base\gameplay\gui\fullscreen\settings\mod_settings_main.inkwidget`

**Version (please complete the following information):**
 - [8.12.2-nightly.2024-01-28]

**Screenshots**
![error](https://github.com/WolvenKit/WolvenKit/assets/60521745/8293cd41-c7e1-4a36-9cb6-d28e9723951a)

[mod_settings_main.zip](https://github.com/WolvenKit/WolvenKit/files/14103205/mod_settings_main.zip)

**Comment by seberoth** [comment]
Thats because WolvenKit currently only supports base game classes. Mod settings (and in fact all mods by @jackhumbert) are highly customized beyond the scope of WolvenKit.

But he is working on support for it. No ETA

**Comment by jackhumbert** [comment]
[Instructions for editing it are described in the readme](https://github.com/jackhumbert/mod_settings?tab=readme-ov-file#development).
