### ISSUE TITLE
WolvenKit fails to parse some streamingsectors

### ISSUE THREAD

**Issue by anon56003269** [WolvenKit/WolvenKit#1593]
**Describe the bug**
This doesn't happen for the vast majority of streamingsectors, but I get an error when trying to parse some of them both when using wscript or just right-click in UI trying to open it. I can create a list of all streamingsectors that can't be parsed if it is helpful.

For example,
Here is the traceback when trying to parse exterior_-21_-1_0_0.streamingsector:

```
[Error    ] Message: Invalid in wolven rtti:"WindowBlindersControllerPS.windowBlindersSkillChecks" [Expected: "CHandle`1" | Got: "CHandle`1"]
Source: WolvenKit.RED4
StackTrace:    at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadClass(RedBaseClass cls, UInt32 size) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.cs:line 97
   at WolvenKit.RED4.Archive.IO.RedPackageReader.ReadBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\RedPackageReader.File.cs:line 127
   at WolvenKit.RED4.Archive.IO.CR2WReader.ParseBuffer(RedBuffer buffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 298
   at WolvenKit.RED4.Archive.IO.CR2WReader.ReadFile(CR2WFile& file, Boolean parseBuffer) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4\Archive\IO\CR2WReader.File.cs:line 151
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4File(BinaryReader br, Boolean parseBuffers, CR2WFile& redFile) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\RED4\Red4ParserService.cs:line 112
[Error    ] Failed to read cr2w file base\worlds\03_night_city\_compiled\default\exterior_-21_-1_0_0.streamingsector
```

**To Reproduce**
1. Search for exterior_-21_-1_0_0.streamingsector in the Asset Browser
2. Right-click on it, and select open without adding to project
3. See error

**Expected behavior**
It should parse the file without error

**Version (please complete the following information):**
 - Version 8.13.0 (and game version is latest 2.12 patch)

**Screenshots**

**Comment by seberoth** [comment]
These files comes with data which is not valid for that file type (by CDPR).
It affects 35 of 47937 streamingsector files. Not much we can do about.
