### ISSUE TITLE
Exception on export morphtarget: Index was out of range

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1604]
While working on that commission where the person wants to play as Reed, I've been running into an issue where I could change the player head just fine, but getting the morphtarget *out* again is impossible.

Latest Nightly (development build), I've created the affected morphtarget 5 minutes earlier with the same version of WKit.

[player_man_average.zip](https://github.com/WolvenKit/WolvenKit/files/14627024/player_man_average.zip)

```
[17/03/2024 11:13:57] [Error    ] Failed to export h0_000_pma__morphs.morphtarget: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[17/03/2024 11:13:57] [Debug    ] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at WolvenKit.RED4.Types.CArrayBase`1.get_Item(Int32 index) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.RED4\Types\Primitives\CArrayBase.cs:line 155
   at WolvenKit.Modkit.RED4.ModTools.GetTargetInfos(CR2WFile cr2w, Int32 subMeshC) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Tools\MorphTargetTools.cs:line 157
   at WolvenKit.Modkit.RED4.ModTools.ExportMorphTargets(CR2WFile cr2w, FileInfo outfile, Boolean isGLBinary, ValidationMode vMode) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Tools\MorphTargetTools.cs:line 48
   at WolvenKit.Modkit.RED4.ModTools.InternalUncookBuffers(CR2WFile cr2wFile, String relPath, FileInfo outfile, GlobalExportArgs settings, DirectoryInfo rawOutDir) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 549
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(CR2WFile cr2wFile, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forceBuffers, Boolean ignoreLookup) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 499
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forceBuffers) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 418
   at WolvenKit.Modkit.RED4.ModTools.Export(FileInfo cr2wFile, GlobalExportArgs args, DirectoryInfo basedir, DirectoryInfo rawOutDir, ECookedFileFormat[] forceBuffers) in C:\Users\manav\Documents\01_coding\_Cyberpunk\WolvenKit\WolvenKit.Modkit\RED4\Export.cs:line 61
```

**Comment by manavortex** [comment]
Would be grand if you could take a look, because I don't even know where to start >.<

**Comment by seberoth** [comment]
Don't know if still present, but looks more like an import error. Could you provide your glb?
![grafik](https://github.com/user-attachments/assets/7681fcef-a0d2-4439-8d14-c58f3da74240)
