### ISSUE TITLE
Unhandled Exception caused by File Information for man_average__cz_stadium_guitarist_01.mesh 

### ISSUE THREAD

**Issue by ArcadieCalliope** [WolvenKit/WolvenKit#1791]
Edit: After messing around a bit more I discovered it isnt't specifically the man_average__cz_stadium_guitarist_01.mesh file, that just happened to be the file I was trying to view when the error occurred. I received the same red text error for every mesh I tried to preview following the first occurrence of the error. Restarting Wolvenkit resolved the issue and allowed me view mesh previews again.

**Describe the bug**
Unhandled Exception when trying to click "zoom to extents" in the File Information for mesh ep1\characters\appearances\quest_temp\proxy\man_average__cz_stadium_guitarist_01\man_average__cz_stadium_guitarist_01.mesh

**To Reproduce**
1. Search for man_average__cz_stadium_guitarist_01.mesh then select it so its information appears in the File Information panel. Select the Mesh tab in File Information
2. In the File Information panel of Wolvenkit right click then attempt to click "zoom to extents" 
3. Log should throw an Unhandled Exception red text warning

**Expected behavior**
Zooming in on the mesh preview in File Information (if it actually has one) and/or no red text warning in the Log panel

**Version (please complete the following information):**
 - Version v8.14.1.0 (nightly release for 2024-06-11)

**Log error warning:**

```[6/11/2024 10:01:42 AM] [Error    ] Message: Object reference not set to an instance of an object.
Source: HelixToolkit.SharpDX.Core
StackTrace:    at HelixToolkit.SharpDX.Core.Model.Scene.ScreenSpacedNode.OnHitTest(HitTestContext context, Matrix totalModelMatrix, List`1& hits)
   at HelixToolkit.SharpDX.Core.Model.Scene.ViewBoxNode.OnHitTest(HitTestContext context, Matrix totalModelMatrix, List`1& hits)
   at HelixToolkit.SharpDX.Core.Model.Scene.SceneNode.HitTest(HitTestContext context, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Element3DCore.HitTest(HitTestContext context, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.ViewBoxHitTest(Point p, InputEventArgs originalInputEventArgs)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.MouseDownHitTest(Point pt, InputEventArgs originalInputEventArgs)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.OnPreviewMouseDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by manavortex** [comment]
This works for me on today's Nightly (13/07), @ArcadieCalliope, can you try to reproduce with a recent version?
