### ISSUE TITLE
Inconsistent handling of submesh LOD names leading to failed mesh imports

### ISSUE THREAD

**Issue by notaspirit** [WolvenKit/WolvenKit#2017]
**Describe the bug**
The mesh exporter exports submeshes with `LOD_0` while the mesh importer refuses to accept them

**To Reproduce**
1. export "base\vehicles\standard\v_standard2_chevalier_thrax\entities\meshes\v_standard2_chevalier_thrax__ext01_chassis_01.mesh" without LOD Filter
2. try to import it back into a `.mesh` from `.glb`

**Expected behavior**
Exported files can be imported without having to rename the submesh names

**Version**
 - 8.15.1-nightly.2024-11-13

**Error Log in Wolvenkit**
`[Error    ] Message: Invalid Geometry/sub mesh name: submesh_09_LOD_0 , Character after "LOD_"  should be 1 or 2 or 4 or 8, Representing the Level of Detail (LOD) of the submesh.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.VerifyGLTF(ModelRoot model, GltfImportArgs args)
   at WolvenKit.Modkit.RED4.ModTools.ImportMesh(FileInfo inGltfFile, Stream inMeshStream, GltfImportArgs args)
   at WolvenKit.Modkit.RED4.ModTools.ImportGltf(RedRelativePath rawRelative, DirectoryInfo outDir, GltfImportArgs args)`

**Comment by seberoth** [comment]
As fas as I remeber LOD_0 was converted to LOD_8 somewhere.
But not 100% certain on that.
