### ISSUE TITLE
Crash Extracting Materials

### ISSUE THREAD

**Issue by Bladehawke** [WolvenKit/WolvenKit#749]
**Describe the bug**
Crash while extracting materials to depot

**To Reproduce**
1. Open a project
2. Click on Extract Materials to Depot
3. Click Generate
4. Wait a few seconds
5. See error

**Expected behavior**
Actual extraction of materials

**Log Excerpt**
```2022-03-20 17:57:32.267 [ERR] Unhandled exception in WolvenKit v8.6.0.0
2022-03-20 17:57:32.325 [ERR] Message: One or more errors occurred. (The process cannot access the file 'F:\WkitDepot\base\characters\common\character_customisation_items\makeup\freckles\red\cheeks__07_red.mi' because it is being used by another process.)
Source: System.Threading.Tasks.Parallel
StackTrace:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at WolvenKit.Views.Dialogs.MaterialsRepositoryDialog.GenerateMaterialRepo(DirectoryInfo materialRepoDir, EUncookExtension texturesExtension) in D:\a\WolvenKit\WolvenKit\WolvenKit\Views\Dialogs\MaterialsRepositoryDialog.xaml.cs:line 98
   at WolvenKit.Views.Dialogs.MaterialsRepositoryDialog.<GenerateButton_Click>b__13_0() in D:\a\WolvenKit\WolvenKit\WolvenKit\Views\Dialogs\MaterialsRepositoryDialog.xaml.cs:line 54
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WolvenKit.Views.Dialogs.MaterialsRepositoryDialog.GenerateButton_Click(Object sender, RoutedEventArgs e) in D:\a\WolvenKit\WolvenKit\WolvenKit\Views\Dialogs\MaterialsRepositoryDialog.xaml.cs:line 54
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge (not that it's relevant :p)
 - Version 8.6.0 Nightly Mar 18

**Comment by ADawesomeguy** [comment]
@Bladehawke please wrap your logs with a \`\`\` above and a \`\`\` below.
