### ISSUE TITLE
Errors Reading Mod Archives

### ISSUE THREAD

**Issue by effs** [WolvenKit/WolvenKit#764]
Found two in my case, dragon might have another:. Without the fix in #763 these will crash wkit when trying to open the mod browser.

**Buffer size doesn't match size in info table.**

Example mod: https://www.nexusmods.com/cyberpunk2077/mods/3728?tab=files (V1 Long)

```
[4/6/2022 6:59:23 PM] Message: Buffer size doesn't match size in info table. 2361 vs 280748
Source: WolvenKit.Core
StackTrace:    at WolvenKit.Core.Compression.Oodle.DecompressAndCopySegment(Stream stream, Stream outStream, UInt32 zSize, UInt32 size) in C:\Users\effs\Code\WolvenKit\main\WolvenKit.Core\Compression\Oodle.cs:line 297
   at WolvenKit.RED4.Archive.IO.ArchiveReader.ReadArchive(String path, IHashService hashService, Archive& ar) in C:\Users\effs\Code\WolvenKit\main\WolvenKit.RED4.Archive\IO\ArchiveReader.cs:line 79
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4Archive(String path, IHashService hashService, Archive& archiveFile) in C:\Users\effs\Code\WolvenKit\main\WolvenKit.Common\RED4\Red4ParserService.cs:line 30
[4/6/2022 6:59:23 PM] Unable to load mod archive: G:\GOG\Cyberpunk 2077\archive\pc\mod\ANRUI_RogueFaceCyberwareLMSRainbowPastel.archive
```

**Access to the path is denied.**

Example mod: https://www.nexusmods.com/cyberpunk2077/mods/1801?tab=files (eyeliner no. 12)

```[4/6/2022 7:48:05 PM] Message: Access to the path is denied.
Source: System.IO.MemoryMappedFiles
StackTrace:    at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at WolvenKit.RED4.Archive.IO.ArchiveReader.ReadArchive(String path, IHashService hashService, Archive& ar) in C:\Users\effs\Code\WolvenKit\main\WolvenKit.RED4.Archive\IO\ArchiveReader.cs:line 73
   at WolvenKit.RED4.CR2W.Red4ParserService.TryReadRed4Archive(String path, IHashService hashService, Archive& archiveFile) in C:\Users\effs\Code\WolvenKit\main\WolvenKit.Common\RED4\Red4ParserService.cs:line 30
[4/6/2022 7:48:05 PM] Unable to load mod archive: G:\GOG\Cyberpunk 2077\archive\pc\mod\basegame_coralinekoralina_line2_12.archive```

**Comment by effs** [comment]
Fixed in #763, awaiting a later better fix.
