### ISSUE TITLE
Meshes cannot be exported using WithMaterials

### ISSUE THREAD

**Issue by Chanka0** [WolvenKit/WolvenKit#884]
**Describe the bug**
Mesh with material is unable to be exported with the corresponding mesh. Mesh can still be exported without the material.

**To Reproduce**
1. Add `int_ent_industrial_a_floor_l300_a.mesh` to project
2. Export with Export Type: WithMaterials, all other options default.
3. Watch as it fails to work.

**Expected behavior**
Mesh would be successfully exported with corresponding Material.json

**Produced Error**
```
[8/18/2022 7:42:50 AM] base\environment\architecture\common\int\int_ent_industrial_a\int_ent_industrial_a_floor_l300_a.mesh - Object reference not set to an instance of an object.
[8/18/2022 7:42:50 AM] Message: Object reference not set to an instance of an object.
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.GetMateriaEntries(CR2WFile cr2w, Stream meshStream, List`1& primaryDependencies, List`1& materialEntryNames, List`1& materialEntries, List`1 archives) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 72
   at WolvenKit.Modkit.RED4.ModTools.ParseMaterials(CR2WFile cr2w, Stream meshStream, FileInfo outfile, List`1 archives, String matRepo, EUncookExtension eUncookExtension) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 256
   at WolvenKit.Modkit.RED4.ModTools.ExportMeshWithMaterials(Stream meshStream, FileInfo outfile, List`1 archives, String matRepo, EUncookExtension eUncookExtension, Boolean isGLBinary, Boolean LodFilter, ValidationMode vmode) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 54
   at WolvenKit.Modkit.RED4.ModTools.HandleMesh(Stream cr2wStream, FileInfo cr2wFileName, MeshExportArgs meshargs) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 526
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 303
```

**Desktop:**
 - OS: Windows 10
 - Version: 8.6.0 and 8.7.0-nightly.2022-08-10

**Extra:**
Someone previously encountered this and created their own fix, which was pulled into the development branch on the same day.
https://github.com/WolvenKit/WolvenKit/pull/813
https://github.com/WolvenKit/WolvenKit/issues/812

Since then it seems that this fix has either been overwritten or a change in the export process has been made. Fixing this would be greatly appreciated, since this issue affects more than just one mesh.

**Comment by seberoth** [comment]
See #898
