### ISSUE TITLE
Asset Browser: Find files using this throw errors

### ISSUE THREAD

**Issue by Neurolinked** [WolvenKit/WolvenKit#913]
**Describe the bug**
in the file Browset using the right click "find files using this command" start the search, throw an error and the searching bar continuosly loop

**To Reproduce**
1. Go to 'Asset browser'
2. Search a file (in my case i tried .ent .mesh and .mt files)
3. Right click on one of the files found
4. Choose 'Find files using this'
5. it Throw an error

```
Message: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
Source: ReactiveUI
StackTrace:    at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Expected behavior**
Find the files that uses the object of the search

**Screenshots**
![image](https://user-images.githubusercontent.com/88206835/192120644-b94b6671-35ce-44cc-943d-088d3888b0ef.png)
![image](https://user-images.githubusercontent.com/88206835/192120604-e645188a-17cc-447e-94bf-33b491e85665.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.7 nightly > 2022-06-16 > 2022-09-23 > 2022-09-24

**Comment by effs** [comment]
Do you have the resources plugin installed?

**Comment by Neurolinked** [comment]
Yes it was installed, i removed it and reinstalled today and it finally work
