### ISSUE TITLE
got  “Attempted to read or write protected memory. This is often an indication that other memory is corrupt” when uncook

### ISSUE THREAD

**Issue by hqqttjiang** [WolvenKit/WolvenKit#935]
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at <Module>.DirectX.SaveToWICFile(DirectX.Image*, DirectX.WIC_FLAGS, _GUID*, Char*, _GUID*, std.function<void __cdecl(IPropertyBag2 *)>*)
--------------------------------
   at DirectXTexNet.ScratchImageImpl.SaveToWICFile(Int32, DirectXTexNet.WIC_FLAGS, System.Guid, System.String)
   at WolvenKit.Modkit.RED4.ModTools.UncookMlmask(System.IO.Stream, System.IO.FileInfo, WolvenKit.Common.Model.Arguments.MlmaskExportArgs)
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(System.IO.Stream, System.String, WolvenKit.Common.Model.Arguments.GlobalExportArgs, System.IO.DirectoryInfo, WolvenKit.Common.ECookedFileFormat[])
   at WolvenKit.Modkit.RED4.ModTools.UncookSingle(WolvenKit.RED4.Archive.ICyberGameArchive, UInt64, System.IO.DirectoryInfo, WolvenKit.Common.Model.Arguments.GlobalExportArgs, System.IO.DirectoryInfo, WolvenKit.Common.ECookedFileFormat[], Boolean)
   at WolvenKit.Modkit.RED4.ModTools+<>c__DisplayClass94_0.<UncookAll>b__2(WolvenKit.RED4.Archive.FileEntry)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.Tasks.TaskReplicator+Replica+<>c.<Execute>b__7_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

this version 8.7.0-nightly.2022-10-03

**Comment by rfuzzo** [comment]
thanks. sigh. this means we need to fix somethings in the dxtex wrapper I guess

**Comment by houseofcat** [comment]
Okay, to catch these in logs in `Release` builds or see them, you have to set the legacy COM access violation policy back on.

```
[10/5/2022 4:43:05 PM] base\environment\decoration\misc\various\tv_stand\textures\tv_stand_a.mlmask And unexpected error occured while uncooking: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[10/5/2022 4:43:05 PM] Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Source: DirectXTexNetImpl
StackTrace:    at DirectX.SaveToWICFile(Image* , WIC_FLAGS , _GUID* , Char* , _GUID* , function<void __cdecl(IPropertyBag2 \*)>* )
   at DirectXTexNet.ScratchImageImpl.SaveToWICFile(Int32 imageIndex, WIC_FLAGS flags, Guid guidContainerFormat, String szFile)
   at WolvenKit.Modkit.RED4.ModTools.UncookMlmask(Stream cr2wStream, FileInfo outfile, MlmaskExportArgs args) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MlmaskTools.cs:line 22
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 418
   at WolvenKit.Modkit.RED4.ModTools.UncookSingleAsync(ICyberGameArchive archive, UInt64 hash, DirectoryInfo outDir, GlobalExportArgs args, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers, Boolean serialize) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 251
[10/5/2022 4:43:05 PM] base\mechanical\mech\mch_002__centaur\textures\ml_mch_002__centaur_legs_masksset.mlmask And unexpected error occured while uncooking: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[10/5/2022 4:43:05 PM] Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Source: DirectXTexNetImpl
StackTrace:    at DirectX.SaveToWICFile(Image* , WIC_FLAGS , _GUID* , Char* , _GUID* , function<void __cdecl(IPropertyBag2 \*)>* )
   at DirectXTexNet.ScratchImageImpl.SaveToWICFile(Int32 imageIndex, WIC_FLAGS flags, Guid guidContainerFormat, String szFile)
   at WolvenKit.Modkit.RED4.ModTools.UncookMlmask(Stream cr2wStream, FileInfo outfile, MlmaskExportArgs args) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MlmaskTools.cs:line 22
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 418
   at WolvenKit.Modkit.RED4.ModTools.UncookSingleAsync(ICyberGameArchive archive, UInt64 hash, DirectoryInfo outDir, GlobalExportArgs args, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers, Boolean serialize) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 251
[10/5/2022 4:43:05 PM] base\mechanical\mech\mch_002__centaur\textures\ml_mch_002__centaur_gun_masksset.mlmask And unexpected error occured while uncooking: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[10/5/2022 4:43:06 PM] Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Source: DirectXTexNetImpl
StackTrace:    at DirectX.SaveToWICFile(Image* , WIC_FLAGS , _GUID* , Char* , _GUID* , function<void __cdecl(IPropertyBag2 \*)>* )
   at DirectXTexNet.ScratchImageImpl.SaveToWICFile(Int32 imageIndex, WIC_FLAGS flags, Guid guidContainerFormat, String szFile)
   at WolvenKit.Modkit.RED4.ModTools.UncookMlmask(Stream cr2wStream, FileInfo outfile, MlmaskExportArgs args) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MlmaskTools.cs:line 22
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 418
   at WolvenKit.Modkit.RED4.ModTools.UncookSingleAsync(ICyberGameArchive archive, UInt64 hash, DirectoryInfo outDir, GlobalExportArgs args, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers, Boolean serialize) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 251
[10/5/2022 4:43:06 PM] base\mechanical\mech\mch_002__centaur\textures\ml_mch_002__centaur_shield_arm_masksset.mlmask And unexpected error occured while uncooking: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[10/5/2022 4:43:06 PM] Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Source: DirectXTexNetImpl
StackTrace:    at DirectX.SaveToWICFile(Image* , WIC_FLAGS , _GUID* , Char* , _GUID* , function<void __cdecl(IPropertyBag2 \*)>* )
   at DirectXTexNet.ScratchImageImpl.SaveToWICFile(Int32 imageIndex, WIC_FLAGS flags, Guid guidContainerFormat, String szFile)
   at WolvenKit.Modkit.RED4.ModTools.UncookMlmask(Stream cr2wStream, FileInfo outfile, MlmaskExportArgs args) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Tools\MlmaskTools.cs:line 22
   at WolvenKit.Modkit.RED4.ModTools.UncookBuffers(Stream cr2wStream, String relPath, GlobalExportArgs settings, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 418
   at WolvenKit.Modkit.RED4.ModTools.UncookSingleAsync(ICyberGameArchive archive, UInt64 hash, DirectoryInfo outDir, GlobalExportArgs args, DirectoryInfo rawOutDir, ECookedFileFormat[] forcebuffers, Boolean serialize) in C:\GitHub\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\Uncook.cs:line 251
```

**Comment by avastar** [comment]
WolvenKit.Console-1.7.0-nightly.2022-09-08 works properly.

**Comment by rfuzzo** [comment]
thank you
