### ISSUE TITLE
Generate Materials Errors

### ISSUE THREAD

**Issue by houseofcat** [WolvenKit/WolvenKit#939]
**Describe the bug**
Fixes and performance tweaks for Generate Materials call.

**To Reproduce**
1. Go to Tools
2. Click on 'Depot Generator'
3. Click on 'Generate Materials'
4. Wait for error.

**Expected behavior**
A couple of exceptions occurring when running Generate Materials.
IndexOutOfRangeException, DivideByZeroException, and Memory Access Violation with DirectX.

**Screenshots**
Uncaught error when previously was in Parallel.ForEach().
```csharp
// Need to add a DivideByZero prevention, something like this.
var smallScale = mWidthLow == 0 ? 0 : maskWidth / mWidthLow;
```

Unsure what triggered this error but happened only once in `Debug`.
```ini
[10/5/2022 11:48:27 AM] Unhandled exception in WolvenKit v8.7.0.0
[10/5/2022 11:48:27 AM] Message: The data area passed to a system call is too small.
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Uncaught error when previously was in Parallel.ForEach().
![image](https://user-images.githubusercontent.com/1414138/194115626-31792a33-834e-4816-841c-57de707832c3.png)

Triggered in `Release` at the very end. Unable to get here in `Debug` as we run out of memory.
![image](https://user-images.githubusercontent.com/1414138/194115597-9cd84a4f-7d91-4538-90d8-639c78b52e51.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Build: Latest debugging locally.

**Comment by rfuzzo** [comment]
fixed in b746e8b992d7aee9278c2b65ecd4d7a2d0ee6de8
