### ISSUE TITLE
Asset Browser: Exception on "Find Files Using This" / "Find Uses"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#972]
**Describe the bug**
"Find files using this" does not work

**To Reproduce**
1. Right-click on base\characters\main_npc\yorinobu_arasaka\t2_001_ma_dress__yourinobu_arasaka_cloth_simulation_animations.anims
2. Select "Find Files using this" from context menu
3. See error

```
[21/10/2022 19:12:09] Unhandled exception in WolvenKit v8.7.0.0
[21/10/2022 19:12:09] Message: SQLite Error 1: 'no such table: Files'.
Source: Microsoft.Data.Sqlite
StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at WolvenKit.ViewModels.Tools.AssetBrowserViewModel.<FindUsing>b__93_0() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\AssetBrowserViewModel.cs:line 286
   at WolvenKit.ViewModels.Tools.AssetBrowserViewModel.FindUsing() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\AssetBrowserViewModel.cs:line 278
```

A similar exception is thrown when selecting "Find Uses" (just different originating method): 
```

[21/10/2022 19:17:19] Unhandled exception in WolvenKit v8.7.0.0
[21/10/2022 19:17:19] Message: SQLite Error 1: 'no such table: Files'.
Source: Microsoft.Data.Sqlite
StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at WolvenKit.ViewModels.Tools.AssetBrowserViewModel.<FindUses>b__97_0() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\AssetBrowserViewModel.cs:line 348
   at WolvenKit.ViewModels.Tools.AssetBrowserViewModel.FindUses() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Tools\AssetBrowserViewModel.cs:line 340
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.7.0-nightly.2022-10-21

**Comment by seberoth** [comment]
Please try to update the WolvenKit Resources plugin

**Comment by manavortex** [comment]
Hey, 
how do I do that? Until now, I've only downloaded the complete nightly release archive.

**Comment by seberoth** [comment]
At the WolvenKit start screen, select Plugins and click install / update at "WolvenKit Resources"

**Comment by manavortex** [comment]
Awesome, that fixed it. Thank you!
